# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGridLayout,
    QGroupBox, QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QSpinBox, QTabWidget, QVBoxLayout, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(990, 820)
        font = QFont()
        font.setPointSize(12)
        Widget.setFont(font)
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(340, 70, 631, 731))
        self.tab_comm = QWidget()
        self.tab_comm.setObjectName(u"tab_comm")
        self.tabWidget.addTab(self.tab_comm, "")
        self.tab_radar = QWidget()
        self.tab_radar.setObjectName(u"tab_radar")
        self.tabWidget.addTab(self.tab_radar, "")
        self.tab_adversarial = QWidget()
        self.tab_adversarial.setObjectName(u"tab_adversarial")
        self.tabWidget.addTab(self.tab_adversarial, "")
        self.tabWidget_ctrl = QTabWidget(Widget)
        self.tabWidget_ctrl.setObjectName(u"tabWidget_ctrl")
        self.tabWidget_ctrl.setGeometry(QRect(20, 180, 301, 400))
        self.tab_tx = QWidget()
        self.tab_tx.setObjectName(u"tab_tx")
        self.groupBox_ctrlTx = QGroupBox(self.tab_tx)
        self.groupBox_ctrlTx.setObjectName(u"groupBox_ctrlTx")
        self.groupBox_ctrlTx.setGeometry(QRect(0, 0, 382, 369))
        self.groupBox_IDAC = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox_IDAC.setObjectName(u"groupBox_IDAC")
        self.groupBox_IDAC.setGeometry(QRect(10, 10, 362, 141))
        self.widget_IDAC = QWidget(self.groupBox_IDAC)
        self.widget_IDAC.setObjectName(u"widget_IDAC")
        self.widget_IDAC.setGeometry(QRect(10, 30, 342, 91))
        self.gridLayout_IDAC = QGridLayout(self.widget_IDAC)
        self.gridLayout_IDAC.setObjectName(u"gridLayout_IDAC")
        self.gridLayout_IDAC.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.widget_IDAC)
        self.label.setObjectName(u"label")
        self.label.setAlignment(Qt.AlignCenter)
        self.gridLayout_IDAC.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QLabel(self.widget_IDAC)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.gridLayout_IDAC.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QLabel(self.widget_IDAC)
        self.label_3.setObjectName(u"label_3")
        self.gridLayout_IDAC.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QLabel(self.widget_IDAC)
        self.label_4.setObjectName(u"label_4")
        self.gridLayout_IDAC.addWidget(self.label_4, 2, 0, 1, 1)
        self.spinBox_IDAC_IP = QSpinBox(self.widget_IDAC)
        self.spinBox_IDAC_IP.setObjectName(u"spinBox_IDAC_IP")
        self.gridLayout_IDAC.addWidget(self.spinBox_IDAC_IP, 1, 1, 1, 1)
        self.spinBox_IDAC_IN = QSpinBox(self.widget_IDAC)
        self.spinBox_IDAC_IN.setObjectName(u"spinBox_IDAC_IN")
        self.gridLayout_IDAC.addWidget(self.spinBox_IDAC_IN, 1, 2, 1, 1)
        self.spinBox_IDAC_QP = QSpinBox(self.widget_IDAC)
        self.spinBox_IDAC_QP.setObjectName(u"spinBox_IDAC_QP")
        self.gridLayout_IDAC.addWidget(self.spinBox_IDAC_QP, 2, 1, 1, 1)
        self.spinBox_IDAC_QN = QSpinBox(self.widget_IDAC)
        self.spinBox_IDAC_QN.setObjectName(u"spinBox_IDAC_QN")
        self.gridLayout_IDAC.addWidget(self.spinBox_IDAC_QN, 2, 2, 1, 1)
        self.groupBox = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 160, 171, 111))
        self.widget_att = QWidget(self.groupBox)
        self.widget_att.setObjectName(u"widget_att")
        self.widget_att.setGeometry(QRect(10, 30, 151, 71))
        self.verticalLayout_att = QVBoxLayout(self.widget_att)
        self.verticalLayout_att.setObjectName(u"verticalLayout_att")
        self.verticalLayout_att.setContentsMargins(0, 0, 0, 0)
        self.checkBox_att2db = QCheckBox(self.widget_att)
        self.checkBox_att2db.setObjectName(u"checkBox_att2db")
        self.verticalLayout_att.addWidget(self.checkBox_att2db)
        self.checkBox_att10db = QCheckBox(self.widget_att)
        self.checkBox_att10db.setObjectName(u"checkBox_att10db")
        self.verticalLayout_att.addWidget(self.checkBox_att10db)
        self.groupBox_BBBW = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox_BBBW.setObjectName(u"groupBox_BBBW")
        self.groupBox_BBBW.setGeometry(QRect(191, 160, 181, 111))
        self.widget_BBBW = QWidget(self.groupBox_BBBW)
        self.widget_BBBW.setObjectName(u"widget_BBBW")
        self.widget_BBBW.setGeometry(QRect(10, 30, 161, 71))
        self.verticalLayout_BBBW = QVBoxLayout(self.widget_BBBW)
        self.verticalLayout_BBBW.setObjectName(u"verticalLayout_BBBW")
        self.verticalLayout_BBBW.setContentsMargins(0, 0, 0, 0)
        self.radioButton_BBBW100M = QRadioButton(self.widget_BBBW)
        self.radioButton_BBBW100M.setObjectName(u"radioButton_BBBW100M")
        self.verticalLayout_BBBW.addWidget(self.radioButton_BBBW100M)
        self.radioButton_BBBW250M = QRadioButton(self.widget_BBBW)
        self.radioButton_BBBW250M.setObjectName(u"radioButton_BBBW250M")
        self.verticalLayout_BBBW.addWidget(self.radioButton_BBBW250M)
        self.radioButton_BBBW500M = QRadioButton(self.widget_BBBW)
        self.radioButton_BBBW500M.setObjectName(u"radioButton_BBBW500M")
        self.radioButton_BBBW500M.setChecked(True)
        self.verticalLayout_BBBW.addWidget(self.radioButton_BBBW500M)
        self.groupBox_gain = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox_gain.setObjectName(u"groupBox_gain")
        self.groupBox_gain.setGeometry(QRect(10, 280, 362, 71))
        self.widget_gain = QWidget(self.groupBox_gain)
        self.widget_gain.setObjectName(u"widget_gain")
        self.widget_gain.setGeometry(QRect(10, 20, 342, 41))
        self.gridLayout_gain = QGridLayout(self.widget_gain)
        self.gridLayout_gain.setObjectName(u"gridLayout_gain")
        self.gridLayout_gain.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.widget_gain)
        self.label_5.setObjectName(u"label_5")
        self.gridLayout_gain.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_BBGain = QComboBox(self.widget_gain)
        self.comboBox_BBGain.setObjectName(u"comboBox_BBGain")
        self.comboBox_BBGain.addItem("")
        self.comboBox_BBGain.addItem("")
        self.comboBox_BBGain.addItem("")
        self.comboBox_BBGain.addItem("")
        self.comboBox_BBGain.setCurrentIndex(1)
        self.gridLayout_gain.addWidget(self.comboBox_BBGain, 0, 1, 1, 1)
        self.label_6 = QLabel(self.widget_gain)
        self.label_6.setObjectName(u"label_6")
        self.gridLayout_gain.addWidget(self.label_6, 0, 2, 1, 1)
        self.comboBox_filterGain = QComboBox(self.widget_gain)
        self.comboBox_filterGain.setObjectName(u"comboBox_filterGain")
        self.comboBox_filterGain.addItem("")
        self.comboBox_filterGain.addItem("")
        self.comboBox_filterGain.addItem("")
        self.comboBox_filterGain.setCurrentIndex(0)
        self.gridLayout_gain.addWidget(self.comboBox_filterGain, 0, 3, 1, 1)
        self.tabWidget_ctrl.addTab(self.tab_tx, "")
        self.tab_rx = QWidget()
        self.tab_rx.setObjectName(u"tab_rx")
        self.groupBox_ctrlRx = QGroupBox(self.tab_rx)
        self.groupBox_ctrlRx.setObjectName(u"groupBox_ctrlRx")
        self.groupBox_ctrlRx.setGeometry(QRect(0, 0, 382, 369))
        self.tabWidget_ctrl.addTab(self.tab_rx, "")
        self.listWidget_console = QListWidget(Widget)
        self.listWidget_console.setObjectName(u"listWidget_console")
        self.listWidget_console.setGeometry(QRect(20, 600, 382, 91))
        self.pushButton_consoleClear = QPushButton(Widget)
        self.pushButton_consoleClear.setObjectName(u"pushButton_consoleClear")
        self.pushButton_consoleClear.setGeometry(QRect(260, 560, 60, 30))
        self.groupBox_udp = QGroupBox(Widget)
        self.groupBox_udp.setObjectName(u"groupBox_udp")
        self.groupBox_udp.setGeometry(QRect(20, 10, 301, 161))
        self.label_localIp = QLabel(self.groupBox_udp)
        self.label_localIp.setObjectName(u"label_localIp")
        self.label_localIp.setGeometry(QRect(10, 30, 61, 30))
        self.label_localPort = QLabel(self.groupBox_udp)
        self.label_localPort.setObjectName(u"label_localPort")
        self.label_localPort.setGeometry(QRect(220, 30, 61, 30))
        self.label_remoteIp = QLabel(self.groupBox_udp)
        self.label_remoteIp.setObjectName(u"label_remoteIp")
        self.label_remoteIp.setGeometry(QRect(10, 70, 61, 30))
        self.label_remotePort = QLabel(self.groupBox_udp)
        self.label_remotePort.setObjectName(u"label_remotePort")
        self.label_remotePort.setGeometry(QRect(220, 70, 61, 30))
        self.lineEdit_localIp = QLineEdit(self.groupBox_udp)
        self.lineEdit_localIp.setObjectName(u"lineEdit_localIp")
        self.lineEdit_localIp.setGeometry(QRect(80, 30, 131, 30))
        self.lineEdit_remoteIp = QLineEdit(self.groupBox_udp)
        self.lineEdit_remoteIp.setObjectName(u"lineEdit_remoteIp")
        self.lineEdit_remoteIp.setGeometry(QRect(80, 70, 131, 30))
        self.spinBox_localPort = QSpinBox(self.groupBox_udp)
        self.spinBox_localPort.setObjectName(u"spinBox_localPort")
        self.spinBox_localPort.setGeometry(QRect(250, 30, 41, 30))
        self.spinBox_localPort.setMaximum(65535)
        self.spinBox_localPort.setValue(1)
        self.spinBox_remotePort = QSpinBox(self.groupBox_udp)
        self.spinBox_remotePort.setObjectName(u"spinBox_remotePort")
        self.spinBox_remotePort.setGeometry(QRect(250, 70, 41, 30))
        self.spinBox_remotePort.setMaximum(65535)
        self.spinBox_remotePort.setValue(2)
        self.pushButton_runStop = QPushButton(self.groupBox_udp)
        self.pushButton_runStop.setObjectName(u"pushButton_runStop")
        self.pushButton_runStop.setGeometry(QRect(10, 120, 81, 30))
        self.horizontalSlider_freq = QSlider(Widget)
        self.horizontalSlider_freq.setObjectName(u"horizontalSlider_freq")
        self.horizontalSlider_freq.setGeometry(QRect(340, 20, 631, 31))
        self.horizontalSlider_freq.setMinimum(20)
        self.horizontalSlider_freq.setMaximum(1800)
        self.horizontalSlider_freq.setOrientation(Qt.Horizontal)
        self.label_freq = QLabel(Widget)
        self.label_freq.setObjectName(u"label_freq")
        self.label_freq.setGeometry(QRect(340, 0, 121, 30))
        self.label_freq_2 = QLabel(Widget)
        self.label_freq_2.setObjectName(u"label_freq_2")
        self.label_freq_2.setGeometry(QRect(340, 60, 161, 30))
        self.label_freq_3 = QLabel(Widget)
        self.label_freq_3.setObjectName(u"label_freq_3")
        self.label_freq_3.setGeometry(QRect(520, 60, 211, 30))

        self.retranslateUi(Widget)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_ctrl.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_comm), QCoreApplication.translate("Widget", u"\u901a\u4fe1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_radar), QCoreApplication.translate("Widget", u"\u96f7\u8fbe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_adversarial), QCoreApplication.translate("Widget", u"\u5bf9\u6297", None))
        self.groupBox_ctrlTx.setTitle("")
        self.groupBox_IDAC.setTitle(QCoreApplication.translate("Widget", u"IDAC", None))
        self.label.setText(QCoreApplication.translate("Widget", u"P", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"N", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"I", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Q", None))
        self.groupBox.setTitle(QCoreApplication.translate("Widget", u"\u8870\u51cf", None))
        self.checkBox_att2db.setText(QCoreApplication.translate("Widget", u"2dB", None))
        self.checkBox_att10db.setText(QCoreApplication.translate("Widget", u"10dB", None))
        self.groupBox_BBBW.setTitle(QCoreApplication.translate("Widget", u"\u5e26\u5bbd", None))
        self.radioButton_BBBW100M.setText(QCoreApplication.translate("Widget", u"100M", None))
        self.radioButton_BBBW250M.setText(QCoreApplication.translate("Widget", u"250M", None))
        self.radioButton_BBBW500M.setText(QCoreApplication.translate("Widget", u"500M", None))
        self.groupBox_gain.setTitle(QCoreApplication.translate("Widget", u"\u589e\u76ca", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"\u57fa\u5e26\u589e\u76ca", None))
        self.comboBox_BBGain.setItemText(0, QCoreApplication.translate("Widget", u"-6dB", None))
        self.comboBox_BBGain.setItemText(1, QCoreApplication.translate("Widget", u"0dB", None))
        self.comboBox_BBGain.setItemText(2, QCoreApplication.translate("Widget", u"6dB", None))
        self.comboBox_BBGain.setItemText(3, QCoreApplication.translate("Widget", u"12dB", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"\u6ee4\u6ce2\u589e\u76ca", None))
        self.comboBox_filterGain.setItemText(0, QCoreApplication.translate("Widget", u"0dB", None))
        self.comboBox_filterGain.setItemText(1, QCoreApplication.translate("Widget", u"6dB", None))
        self.comboBox_filterGain.setItemText(2, QCoreApplication.translate("Widget", u"12dB", None))
        self.tabWidget_ctrl.setTabText(self.tabWidget_ctrl.indexOf(self.tab_tx), QCoreApplication.translate("Widget", u"Tx\u63a7\u5236", None))
        self.groupBox_ctrlRx.setTitle("")
        self.tabWidget_ctrl.setTabText(self.tabWidget_ctrl.indexOf(self.tab_rx), QCoreApplication.translate("Widget", u"Rx\u63a7\u5236", None))
        self.pushButton_consoleClear.setText(QCoreApplication.translate("Widget", u"\u6e05\u7a7a", None))
        self.groupBox_udp.setTitle(QCoreApplication.translate("Widget", u"UDP \u8fde\u63a5", None))
        self.label_localIp.setText(QCoreApplication.translate("Widget", u"\u672c\u673a IP", None))
        self.label_localPort.setText(QCoreApplication.translate("Widget", u"\u7aef\u53e3", None))
        self.label_remoteIp.setText(QCoreApplication.translate("Widget", u"\u76ee\u6807 IP", None))
        self.label_remotePort.setText(QCoreApplication.translate("Widget", u"\u7aef\u53e3", None))
        self.lineEdit_localIp.setText(QCoreApplication.translate("Widget", u"192.168.240.1", None))
        self.lineEdit_remoteIp.setText(QCoreApplication.translate("Widget", u"192.168.240.2", None))
        self.pushButton_runStop.setText(QCoreApplication.translate("Widget", u"\u5f00\u59cb\u8fde\u63a5", None))
        self.label_freq.setText(QCoreApplication.translate("Widget", u"\u9891\u7387\uff1a0.3GHz", None))
        self.label_freq_2.setText(QCoreApplication.translate("Widget", u"\u2191 2GHz\uff1a\u94fe\u8def\u5207\u6362", None))
        self.label_freq_3.setText(QCoreApplication.translate("Widget", u"\u2191 6GHz\uff1a\u94fe\u8def\u5207\u6362/LH\u5207\u6362", None))
    # retranslateUi

