# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QListWidget, QListWidgetItem, QPushButton,
    QRadioButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(990, 820)
        font = QFont()
        font.setPointSize(12)
        Widget.setFont(font)
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(340, 70, 631, 731))
        self.tab_comm = QWidget()
        self.tab_comm.setObjectName(u"tab_comm")
        self.tabWidget.addTab(self.tab_comm, "")
        self.tab_radar = QWidget()
        self.tab_radar.setObjectName(u"tab_radar")
        self.tabWidget.addTab(self.tab_radar, "")
        self.tab_adversarial = QWidget()
        self.tab_adversarial.setObjectName(u"tab_adversarial")
        self.tabWidget.addTab(self.tab_adversarial, "")
        self.groupBox_ctrlTx = QGroupBox(Widget)
        self.groupBox_ctrlTx.setObjectName(u"groupBox_ctrlTx")
        self.groupBox_ctrlTx.setGeometry(QRect(20, 130, 301, 321))
        self.groupBox_IDAC = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox_IDAC.setObjectName(u"groupBox_IDAC")
        self.groupBox_IDAC.setGeometry(QRect(10, 30, 191, 131))
        self.spinBox_IDAC_IP = QSpinBox(self.groupBox_IDAC)
        self.spinBox_IDAC_IP.setObjectName(u"spinBox_IDAC_IP")
        self.spinBox_IDAC_IP.setGeometry(QRect(40, 50, 61, 30))
        self.label = QLabel(self.groupBox_IDAC)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 20, 21, 30))
        self.label_2 = QLabel(self.groupBox_IDAC)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(150, 20, 21, 30))
        self.label_3 = QLabel(self.groupBox_IDAC)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 21, 30))
        self.label_4 = QLabel(self.groupBox_IDAC)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 90, 21, 30))
        self.spinBox_IDAC_IN = QSpinBox(self.groupBox_IDAC)
        self.spinBox_IDAC_IN.setObjectName(u"spinBox_IDAC_IN")
        self.spinBox_IDAC_IN.setGeometry(QRect(120, 50, 61, 30))
        self.spinBox_IDAC_QP = QSpinBox(self.groupBox_IDAC)
        self.spinBox_IDAC_QP.setObjectName(u"spinBox_IDAC_QP")
        self.spinBox_IDAC_QP.setGeometry(QRect(40, 90, 61, 30))
        self.spinBox_IDAC_QN = QSpinBox(self.groupBox_IDAC)
        self.spinBox_IDAC_QN.setObjectName(u"spinBox_IDAC_QN")
        self.spinBox_IDAC_QN.setGeometry(QRect(120, 90, 61, 30))
        self.groupBox = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(210, 30, 81, 131))
        self.checkBox_att2db = QCheckBox(self.groupBox)
        self.checkBox_att2db.setObjectName(u"checkBox_att2db")
        self.checkBox_att2db.setGeometry(QRect(10, 50, 61, 30))
        self.checkBox_att10db = QCheckBox(self.groupBox)
        self.checkBox_att10db.setObjectName(u"checkBox_att10db")
        self.checkBox_att10db.setGeometry(QRect(10, 90, 61, 30))
        self.groupBox_BBBW = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox_BBBW.setObjectName(u"groupBox_BBBW")
        self.groupBox_BBBW.setGeometry(QRect(10, 170, 281, 61))
        self.radioButton_BBBW100M = QRadioButton(self.groupBox_BBBW)
        self.radioButton_BBBW100M.setObjectName(u"radioButton_BBBW100M")
        self.radioButton_BBBW100M.setGeometry(QRect(10, 20, 71, 30))
        self.radioButton_BBBW250M = QRadioButton(self.groupBox_BBBW)
        self.radioButton_BBBW250M.setObjectName(u"radioButton_BBBW250M")
        self.radioButton_BBBW250M.setGeometry(QRect(90, 20, 71, 30))
        self.radioButton_BBBW500M = QRadioButton(self.groupBox_BBBW)
        self.radioButton_BBBW500M.setObjectName(u"radioButton_BBBW500M")
        self.radioButton_BBBW500M.setGeometry(QRect(170, 20, 71, 30))
        self.radioButton_BBBW500M.setChecked(True)
        self.comboBox_BBGain = QComboBox(self.groupBox_ctrlTx)
        self.comboBox_BBGain.setObjectName(u"comboBox_BBGain")
        self.comboBox_BBGain.setGeometry(QRect(80, 240, 61, 30))
        self.label_5 = QLabel(self.groupBox_ctrlTx)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 240, 91, 30))
        self.label_6 = QLabel(self.groupBox_ctrlTx)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 240, 91, 30))
        self.comboBox_filterGain = QComboBox(self.groupBox_ctrlTx)
        self.comboBox_filterGain.setObjectName(u"comboBox_filterGain")
        self.comboBox_filterGain.setGeometry(QRect(230, 240, 61, 30))
        self.label_7 = QLabel(self.groupBox_ctrlTx)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 280, 31, 30))
        self.comboBox_DLL = QComboBox(self.groupBox_ctrlTx)
        self.comboBox_DLL.setObjectName(u"comboBox_DLL")
        self.comboBox_DLL.setGeometry(QRect(60, 280, 141, 30))
        self.groupBox_ctrlRx = QGroupBox(Widget)
        self.groupBox_ctrlRx.setObjectName(u"groupBox_ctrlRx")
        self.groupBox_ctrlRx.setGeometry(QRect(20, 460, 301, 201))
        self.listWidget_console = QListWidget(Widget)
        self.listWidget_console.setObjectName(u"listWidget_console")
        self.listWidget_console.setGeometry(QRect(20, 710, 301, 91))
        self.pushButton_consoleClear = QPushButton(Widget)
        self.pushButton_consoleClear.setObjectName(u"pushButton_consoleClear")
        self.pushButton_consoleClear.setGeometry(QRect(260, 670, 60, 30))
        self.horizontalSlider_freq = QSlider(Widget)
        self.horizontalSlider_freq.setObjectName(u"horizontalSlider_freq")
        self.horizontalSlider_freq.setGeometry(QRect(140, 10, 831, 31))
        self.horizontalSlider_freq.setMinimum(30)
        self.horizontalSlider_freq.setMaximum(1800)
        self.horizontalSlider_freq.setOrientation(Qt.Horizontal)
        self.label_freq = QLabel(Widget)
        self.label_freq.setObjectName(u"label_freq")
        self.label_freq.setGeometry(QRect(20, 10, 121, 30))
        self.pushButton_runStop = QPushButton(Widget)
        self.pushButton_runStop.setObjectName(u"pushButton_runStop")
        self.pushButton_runStop.setGeometry(QRect(20, 70, 60, 30))
        self.label_freq_2 = QLabel(Widget)
        self.label_freq_2.setObjectName(u"label_freq_2")
        self.label_freq_2.setGeometry(QRect(220, 30, 141, 30))
        self.label_freq_3 = QLabel(Widget)
        self.label_freq_3.setObjectName(u"label_freq_3")
        self.label_freq_3.setGeometry(QRect(410, 30, 211, 30))

        self.retranslateUi(Widget)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_comm), QCoreApplication.translate("Widget", u"\u901a\u4fe1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_radar), QCoreApplication.translate("Widget", u"\u96f7\u8fbe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_adversarial), QCoreApplication.translate("Widget", u"\u5bf9\u6297", None))
        self.groupBox_ctrlTx.setTitle(QCoreApplication.translate("Widget", u"Tx\u63a7\u5236", None))
        self.groupBox_IDAC.setTitle(QCoreApplication.translate("Widget", u"IDAC", None))
        self.label.setText(QCoreApplication.translate("Widget", u"P", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"N", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"I", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Q", None))
        self.groupBox.setTitle(QCoreApplication.translate("Widget", u"\u8870\u51cf", None))
        self.checkBox_att2db.setText(QCoreApplication.translate("Widget", u"2dB", None))
        self.checkBox_att10db.setText(QCoreApplication.translate("Widget", u"10dB", None))
        self.groupBox_BBBW.setTitle(QCoreApplication.translate("Widget", u"\u5e26\u5bbd", None))
        self.radioButton_BBBW100M.setText(QCoreApplication.translate("Widget", u"100M", None))
        self.radioButton_BBBW250M.setText(QCoreApplication.translate("Widget", u"250M", None))
        self.radioButton_BBBW500M.setText(QCoreApplication.translate("Widget", u"500M", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"\u57fa\u5e26\u589e\u76ca", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"\u6ee4\u6ce2\u589e\u76ca", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"DLL", None))
        self.groupBox_ctrlRx.setTitle(QCoreApplication.translate("Widget", u"Rx\u63a7\u5236", None))
        self.pushButton_consoleClear.setText(QCoreApplication.translate("Widget", u"\u6e05\u7a7a", None))
        self.label_freq.setText(QCoreApplication.translate("Widget", u"\u9891\u7387\uff1a0.3GHz", None))
        self.pushButton_runStop.setText(QCoreApplication.translate("Widget", u"\u542f\u52a8", None))
        self.label_freq_2.setText(QCoreApplication.translate("Widget", u"\u2191 2GHz\uff1a\u94fe\u8def\u5207\u6362", None))
        self.label_freq_3.setText(QCoreApplication.translate("Widget", u"\u2191 6GHz\uff1a\u94fe\u8def\u5207\u6362/LH\u5207\u6362", None))
    # retranslateUi

