# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QListWidget, QListWidgetItem, QPushButton,
    QRadioButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QTextEdit, QVBoxLayout, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(1280, 900)
        Widget.setMinimumSize(QSize(1000, 500))
        font = QFont()
        font.setPointSize(12)
        Widget.setFont(font)
        self.label_freq = QLabel(Widget)
        self.label_freq.setObjectName(u"label_freq")
        self.label_freq.setGeometry(QRect(10, 10, 113, 30))
        self.horizontalSlider_freq = QSlider(Widget)
        self.horizontalSlider_freq.setObjectName(u"horizontalSlider_freq")
        self.horizontalSlider_freq.setGeometry(QRect(140, 18, 1131, 18))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_freq.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_freq.setSizePolicy(sizePolicy)
        self.horizontalSlider_freq.setMinimum(20)
        self.horizontalSlider_freq.setMaximum(1800)
        self.horizontalSlider_freq.setOrientation(Qt.Horizontal)
        self.label_freq_2 = QLabel(Widget)
        self.label_freq_2.setObjectName(u"label_freq_2")
        self.label_freq_2.setEnabled(True)
        self.label_freq_2.setGeometry(QRect(260, 40, 135, 21))
        self.label_freq_2.setLayoutDirection(Qt.LeftToRight)
        self.label_freq_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_freq_3 = QLabel(Widget)
        self.label_freq_3.setObjectName(u"label_freq_3")
        self.label_freq_3.setGeometry(QRect(510, 40, 194, 21))
        self.tabWidget_ctrl = QTabWidget(Widget)
        self.tabWidget_ctrl.setObjectName(u"tabWidget_ctrl")
        self.tabWidget_ctrl.setGeometry(QRect(10, 70, 271, 571))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tabWidget_ctrl.sizePolicy().hasHeightForWidth())
        self.tabWidget_ctrl.setSizePolicy(sizePolicy1)
        self.tab_tx = QWidget()
        self.tab_tx.setObjectName(u"tab_tx")
        self.tab_tx_layout = QVBoxLayout(self.tab_tx)
        self.tab_tx_layout.setSpacing(10)
        self.tab_tx_layout.setObjectName(u"tab_tx_layout")
        self.tab_tx_layout.setContentsMargins(10, 10, 10, 10)
        self.groupBox_ctrlTx = QGroupBox(self.tab_tx)
        self.groupBox_ctrlTx.setObjectName(u"groupBox_ctrlTx")
        self.groupBox_IDAC = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox_IDAC.setObjectName(u"groupBox_IDAC")
        self.groupBox_IDAC.setGeometry(QRect(10, 10, 221, 141))
        self.label = QLabel(self.groupBox_IDAC)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(35, 31, 16, 30))
        self.label_2 = QLabel(self.groupBox_IDAC)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(120, 31, 16, 30))
        self.spinBox_T_IDAC_IP = QSpinBox(self.groupBox_IDAC)
        self.spinBox_T_IDAC_IP.setObjectName(u"spinBox_T_IDAC_IP")
        self.spinBox_T_IDAC_IP.setGeometry(QRect(35, 66, 75, 30))
        self.spinBox_T_IDAC_IN = QSpinBox(self.groupBox_IDAC)
        self.spinBox_T_IDAC_IN.setObjectName(u"spinBox_T_IDAC_IN")
        self.spinBox_T_IDAC_IN.setGeometry(QRect(120, 66, 75, 30))
        self.spinBox_T_IDAC_QP = QSpinBox(self.groupBox_IDAC)
        self.spinBox_T_IDAC_QP.setObjectName(u"spinBox_T_IDAC_QP")
        self.spinBox_T_IDAC_QP.setGeometry(QRect(35, 103, 75, 30))
        self.spinBox_T_IDAC_QN = QSpinBox(self.groupBox_IDAC)
        self.spinBox_T_IDAC_QN.setObjectName(u"spinBox_T_IDAC_QN")
        self.spinBox_T_IDAC_QN.setGeometry(QRect(120, 103, 75, 30))
        self.label_4 = QLabel(self.groupBox_IDAC)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(11, 103, 16, 30))
        self.label_3 = QLabel(self.groupBox_IDAC)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(11, 66, 16, 30))
        self.groupBox = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 280, 221, 111))
        self.checkBox_T_att2db = QCheckBox(self.groupBox)
        self.checkBox_T_att2db.setObjectName(u"checkBox_T_att2db")
        self.checkBox_T_att2db.setGeometry(QRect(12, 30, 62, 30))
        self.checkBox_T_att10db = QCheckBox(self.groupBox)
        self.checkBox_T_att10db.setObjectName(u"checkBox_T_att10db")
        self.checkBox_T_att10db.setGeometry(QRect(12, 70, 72, 30))
        self.groupBox_gain = QGroupBox(self.groupBox_ctrlTx)
        self.groupBox_gain.setObjectName(u"groupBox_gain")
        self.groupBox_gain.setGeometry(QRect(10, 160, 221, 111))
        self.label_5 = QLabel(self.groupBox_gain)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 32, 64, 30))
        self.label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_T_BBGain = QComboBox(self.groupBox_gain)
        self.comboBox_T_BBGain.addItem("")
        self.comboBox_T_BBGain.addItem("")
        self.comboBox_T_BBGain.addItem("")
        self.comboBox_T_BBGain.addItem("")
        self.comboBox_T_BBGain.setObjectName(u"comboBox_T_BBGain")
        self.comboBox_T_BBGain.setGeometry(QRect(90, 30, 75, 30))
        self.label_6 = QLabel(self.groupBox_gain)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 64, 30))
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_T_filterGain = QComboBox(self.groupBox_gain)
        self.comboBox_T_filterGain.addItem("")
        self.comboBox_T_filterGain.addItem("")
        self.comboBox_T_filterGain.addItem("")
        self.comboBox_T_filterGain.setObjectName(u"comboBox_T_filterGain")
        self.comboBox_T_filterGain.setGeometry(QRect(90, 70, 75, 30))

        self.tab_tx_layout.addWidget(self.groupBox_ctrlTx)

        self.tabWidget_ctrl.addTab(self.tab_tx, "")
        self.tab_rx = QWidget()
        self.tab_rx.setObjectName(u"tab_rx")
        self.tab_rx_layout = QVBoxLayout(self.tab_rx)
        self.tab_rx_layout.setSpacing(10)
        self.tab_rx_layout.setObjectName(u"tab_rx_layout")
        self.tab_rx_layout.setContentsMargins(10, 10, 10, 10)
        self.groupBox_ctrlRx = QGroupBox(self.tab_rx)
        self.groupBox_ctrlRx.setObjectName(u"groupBox_ctrlRx")
        self.groupBox_IDAC_4 = QGroupBox(self.groupBox_ctrlRx)
        self.groupBox_IDAC_4.setObjectName(u"groupBox_IDAC_4")
        self.groupBox_IDAC_4.setGeometry(QRect(10, 10, 221, 141))
        self.label_19 = QLabel(self.groupBox_IDAC_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(35, 31, 16, 30))
        self.label_20 = QLabel(self.groupBox_IDAC_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(120, 31, 16, 30))
        self.spinBox_R_IDAC1_IP = QSpinBox(self.groupBox_IDAC_4)
        self.spinBox_R_IDAC1_IP.setObjectName(u"spinBox_R_IDAC1_IP")
        self.spinBox_R_IDAC1_IP.setGeometry(QRect(35, 66, 75, 30))
        self.spinBox_R_IDAC1_IN = QSpinBox(self.groupBox_IDAC_4)
        self.spinBox_R_IDAC1_IN.setObjectName(u"spinBox_R_IDAC1_IN")
        self.spinBox_R_IDAC1_IN.setGeometry(QRect(120, 66, 75, 30))
        self.spinBox_R_IDAC1_QP = QSpinBox(self.groupBox_IDAC_4)
        self.spinBox_R_IDAC1_QP.setObjectName(u"spinBox_R_IDAC1_QP")
        self.spinBox_R_IDAC1_QP.setGeometry(QRect(35, 103, 75, 30))
        self.spinBox_R_IDAC1_QN = QSpinBox(self.groupBox_IDAC_4)
        self.spinBox_R_IDAC1_QN.setObjectName(u"spinBox_R_IDAC1_QN")
        self.spinBox_R_IDAC1_QN.setGeometry(QRect(120, 103, 75, 30))
        self.label_21 = QLabel(self.groupBox_IDAC_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(11, 103, 16, 30))
        self.label_22 = QLabel(self.groupBox_IDAC_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(11, 66, 16, 30))
        self.groupBox_gain_4 = QGroupBox(self.groupBox_ctrlRx)
        self.groupBox_gain_4.setObjectName(u"groupBox_gain_4")
        self.groupBox_gain_4.setGeometry(QRect(10, 310, 221, 191))
        self.label_23 = QLabel(self.groupBox_gain_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(40, 112, 64, 30))
        self.label_23.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_R_BBGain = QComboBox(self.groupBox_gain_4)
        self.comboBox_R_BBGain.addItem("")
        self.comboBox_R_BBGain.addItem("")
        self.comboBox_R_BBGain.addItem("")
        self.comboBox_R_BBGain.addItem("")
        self.comboBox_R_BBGain.setObjectName(u"comboBox_R_BBGain")
        self.comboBox_R_BBGain.setGeometry(QRect(120, 110, 75, 30))
        self.label_24 = QLabel(self.groupBox_gain_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 30, 100, 30))
        self.label_24.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_R_filterGain1 = QComboBox(self.groupBox_gain_4)
        self.comboBox_R_filterGain1.addItem("")
        self.comboBox_R_filterGain1.addItem("")
        self.comboBox_R_filterGain1.addItem("")
        self.comboBox_R_filterGain1.setObjectName(u"comboBox_R_filterGain1")
        self.comboBox_R_filterGain1.setGeometry(QRect(120, 30, 75, 30))
        self.label_25 = QLabel(self.groupBox_gain_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 70, 100, 30))
        self.label_25.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_R_filterGain2 = QComboBox(self.groupBox_gain_4)
        self.comboBox_R_filterGain2.addItem("")
        self.comboBox_R_filterGain2.addItem("")
        self.comboBox_R_filterGain2.addItem("")
        self.comboBox_R_filterGain2.setObjectName(u"comboBox_R_filterGain2")
        self.comboBox_R_filterGain2.setGeometry(QRect(120, 70, 75, 30))
        self.label_30 = QLabel(self.groupBox_gain_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(40, 150, 64, 30))
        self.label_30.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_R_TIAGain = QComboBox(self.groupBox_gain_4)
        self.comboBox_R_TIAGain.addItem("")
        self.comboBox_R_TIAGain.addItem("")
        self.comboBox_R_TIAGain.addItem("")
        self.comboBox_R_TIAGain.setObjectName(u"comboBox_R_TIAGain")
        self.comboBox_R_TIAGain.setGeometry(QRect(120, 150, 75, 30))
        self.groupBox_IDAC_5 = QGroupBox(self.groupBox_ctrlRx)
        self.groupBox_IDAC_5.setObjectName(u"groupBox_IDAC_5")
        self.groupBox_IDAC_5.setGeometry(QRect(10, 160, 221, 141))
        self.label_26 = QLabel(self.groupBox_IDAC_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(35, 31, 16, 30))
        self.label_27 = QLabel(self.groupBox_IDAC_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(120, 31, 16, 30))
        self.spinBox_R_IDAC2_IP = QSpinBox(self.groupBox_IDAC_5)
        self.spinBox_R_IDAC2_IP.setObjectName(u"spinBox_R_IDAC2_IP")
        self.spinBox_R_IDAC2_IP.setGeometry(QRect(35, 66, 75, 30))
        self.spinBox_R_IDAC2_IN = QSpinBox(self.groupBox_IDAC_5)
        self.spinBox_R_IDAC2_IN.setObjectName(u"spinBox_R_IDAC2_IN")
        self.spinBox_R_IDAC2_IN.setGeometry(QRect(120, 66, 75, 30))
        self.spinBox_R_IDAC2_QP = QSpinBox(self.groupBox_IDAC_5)
        self.spinBox_R_IDAC2_QP.setObjectName(u"spinBox_R_IDAC2_QP")
        self.spinBox_R_IDAC2_QP.setGeometry(QRect(35, 103, 75, 30))
        self.spinBox_R_IDAC2_QN = QSpinBox(self.groupBox_IDAC_5)
        self.spinBox_R_IDAC2_QN.setObjectName(u"spinBox_R_IDAC2_QN")
        self.spinBox_R_IDAC2_QN.setGeometry(QRect(120, 103, 75, 30))
        self.label_28 = QLabel(self.groupBox_IDAC_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(11, 103, 16, 30))
        self.label_29 = QLabel(self.groupBox_IDAC_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(11, 66, 16, 30))

        self.tab_rx_layout.addWidget(self.groupBox_ctrlRx)

        self.tabWidget_ctrl.addTab(self.tab_rx, "")
        self.groupBox_BBBW = QGroupBox(Widget)
        self.groupBox_BBBW.setObjectName(u"groupBox_BBBW")
        self.groupBox_BBBW.setGeometry(QRect(10, 650, 271, 72))
        self.radioButton_BBBW100M = QRadioButton(self.groupBox_BBBW)
        self.radioButton_BBBW100M.setObjectName(u"radioButton_BBBW100M")
        self.radioButton_BBBW100M.setGeometry(QRect(12, 35, 67, 25))
        self.radioButton_BBBW250M = QRadioButton(self.groupBox_BBBW)
        self.radioButton_BBBW250M.setObjectName(u"radioButton_BBBW250M")
        self.radioButton_BBBW250M.setGeometry(QRect(96, 35, 67, 25))
        self.radioButton_BBBW500M = QRadioButton(self.groupBox_BBBW)
        self.radioButton_BBBW500M.setObjectName(u"radioButton_BBBW500M")
        self.radioButton_BBBW500M.setGeometry(QRect(181, 35, 67, 25))
        self.radioButton_BBBW500M.setChecked(True)
        self.listWidget_console = QListWidget(Widget)
        self.listWidget_console.setObjectName(u"listWidget_console")
        self.listWidget_console.setGeometry(QRect(10, 800, 1261, 91))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(1)
        sizePolicy2.setHeightForWidth(self.listWidget_console.sizePolicy().hasHeightForWidth())
        self.listWidget_console.setSizePolicy(sizePolicy2)
        self.pushButton_consoleClear = QPushButton(Widget)
        self.pushButton_consoleClear.setObjectName(u"pushButton_consoleClear")
        self.pushButton_consoleClear.setGeometry(QRect(200, 760, 81, 31))
        self.tabWidget = QTabWidget(Widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(300, 70, 971, 721))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(1)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy3)
        self.tab_comm = QWidget()
        self.tab_comm.setObjectName(u"tab_comm")
        self.groupBox_2 = QGroupBox(self.tab_comm)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 30, 951, 281))
        self.textEdit_commR = QTextEdit(self.groupBox_2)
        self.textEdit_commR.setObjectName(u"textEdit_commR")
        self.textEdit_commR.setGeometry(QRect(10, 100, 501, 171))
        self.textEdit_commR.setReadOnly(True)
        self.label_freq_4 = QLabel(self.groupBox_2)
        self.label_freq_4.setObjectName(u"label_freq_4")
        self.label_freq_4.setEnabled(True)
        self.label_freq_4.setGeometry(QRect(10, 60, 151, 30))
        self.label_freq_4.setLayoutDirection(Qt.LeftToRight)
        self.label_freq_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_freq_5 = QLabel(self.groupBox_2)
        self.label_freq_5.setObjectName(u"label_freq_5")
        self.label_freq_5.setEnabled(True)
        self.label_freq_5.setGeometry(QRect(370, 60, 151, 30))
        self.label_freq_5.setLayoutDirection(Qt.LeftToRight)
        self.label_freq_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_commImgR = QLabel(self.groupBox_2)
        self.label_commImgR.setObjectName(u"label_commImgR")
        self.label_commImgR.setEnabled(True)
        self.label_commImgR.setGeometry(QRect(520, 40, 421, 231))
        self.label_commImgR.setLayoutDirection(Qt.LeftToRight)
        self.label_commImgR.setStyleSheet(u"border-width: 3px;border-style: solid;border-color: black;")
        self.label_commImgR.setAlignment(Qt.AlignCenter)
        self.pushButton_commRunStop = QPushButton(self.groupBox_2)
        self.pushButton_commRunStop.setObjectName(u"pushButton_commRunStop")
        self.pushButton_commRunStop.setGeometry(QRect(10, 30, 141, 30))
        self.groupBox_3 = QGroupBox(self.tab_comm)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 350, 951, 321))
        self.label_commImgT = QLabel(self.groupBox_3)
        self.label_commImgT.setObjectName(u"label_commImgT")
        self.label_commImgT.setEnabled(True)
        self.label_commImgT.setGeometry(QRect(520, 40, 421, 231))
        self.label_commImgT.setLayoutDirection(Qt.LeftToRight)
        self.label_commImgT.setStyleSheet(u"border-width: 3px;border-style: solid;border-color: black;")
        self.label_commImgT.setAlignment(Qt.AlignCenter)
        self.label_freq_6 = QLabel(self.groupBox_3)
        self.label_freq_6.setObjectName(u"label_freq_6")
        self.label_freq_6.setEnabled(True)
        self.label_freq_6.setGeometry(QRect(370, 60, 151, 30))
        self.label_freq_6.setLayoutDirection(Qt.LeftToRight)
        self.label_freq_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_freq_7 = QLabel(self.groupBox_3)
        self.label_freq_7.setObjectName(u"label_freq_7")
        self.label_freq_7.setEnabled(True)
        self.label_freq_7.setGeometry(QRect(10, 60, 151, 30))
        self.label_freq_7.setLayoutDirection(Qt.LeftToRight)
        self.label_freq_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.textEdit_commT = QTextEdit(self.groupBox_3)
        self.textEdit_commT.setObjectName(u"textEdit_commT")
        self.textEdit_commT.setGeometry(QRect(10, 100, 501, 171))
        self.pushButton_commImgT = QPushButton(self.groupBox_3)
        self.pushButton_commImgT.setObjectName(u"pushButton_commImgT")
        self.pushButton_commImgT.setGeometry(QRect(740, 280, 141, 30))
        self.pushButton_commTextT = QPushButton(self.groupBox_3)
        self.pushButton_commTextT.setObjectName(u"pushButton_commTextT")
        self.pushButton_commTextT.setGeometry(QRect(190, 280, 141, 30))
        self.pushButton_commImgSelect = QPushButton(self.groupBox_3)
        self.pushButton_commImgSelect.setObjectName(u"pushButton_commImgSelect")
        self.pushButton_commImgSelect.setGeometry(QRect(580, 280, 141, 30))
        self.radioButton_commR = QRadioButton(self.tab_comm)
        self.radioButton_commR.setObjectName(u"radioButton_commR")
        self.radioButton_commR.setGeometry(QRect(70, 10, 151, 30))
        self.radioButton_commR.setChecked(True)
        self.radioButton_commT = QRadioButton(self.tab_comm)
        self.radioButton_commT.setObjectName(u"radioButton_commT")
        self.radioButton_commT.setGeometry(QRect(70, 330, 151, 30))
        self.tabWidget.addTab(self.tab_comm, "")
        self.tab_radar = QWidget()
        self.tab_radar.setObjectName(u"tab_radar")
        self.pushButton_runStop = QPushButton(self.tab_radar)
        self.pushButton_runStop.setObjectName(u"pushButton_runStop")
        self.pushButton_runStop.setGeometry(QRect(820, 40, 121, 30))
        self.tabWidget.addTab(self.tab_radar, "")
        self.tab_adversarial = QWidget()
        self.tab_adversarial.setObjectName(u"tab_adversarial")
        self.tabWidget.addTab(self.tab_adversarial, "")
        self.groupBox_4 = QGroupBox(Widget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(1300, 80, 171, 241))
        self.pushButton_rxConfigSend = QPushButton(self.groupBox_4)
        self.pushButton_rxConfigSend.setObjectName(u"pushButton_rxConfigSend")
        self.pushButton_rxConfigSend.setGeometry(QRect(20, 90, 101, 31))
        self.pushButton_txConfigSend = QPushButton(self.groupBox_4)
        self.pushButton_txConfigSend.setObjectName(u"pushButton_txConfigSend")
        self.pushButton_txConfigSend.setGeometry(QRect(20, 50, 100, 31))

        self.retranslateUi(Widget)

        self.tabWidget_ctrl.setCurrentIndex(0)
        self.comboBox_T_BBGain.setCurrentIndex(0)
        self.comboBox_T_filterGain.setCurrentIndex(0)
        self.comboBox_R_BBGain.setCurrentIndex(1)
        self.comboBox_R_filterGain1.setCurrentIndex(0)
        self.comboBox_R_filterGain2.setCurrentIndex(0)
        self.comboBox_R_TIAGain.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Widget", None))
        self.label_freq.setText(QCoreApplication.translate("Widget", u"\u9891\u7387\uff1a0.20GHz", None))
        self.label_freq_2.setText(QCoreApplication.translate("Widget", u"\u2191 2GHz\uff1a\u94fe\u8def\u5207\u6362", None))
        self.label_freq_3.setText(QCoreApplication.translate("Widget", u"\u2191 6GHz\uff1a\u94fe\u8def\u5207\u6362/LH\u5207\u6362", None))
        self.groupBox_ctrlTx.setTitle("")
        self.groupBox_IDAC.setTitle(QCoreApplication.translate("Widget", u"IDAC", None))
        self.label.setText(QCoreApplication.translate("Widget", u"P", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"N", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"Q", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"I", None))
        self.groupBox.setTitle(QCoreApplication.translate("Widget", u"\u8870\u51cf", None))
        self.checkBox_T_att2db.setText(QCoreApplication.translate("Widget", u"2dB", None))
        self.checkBox_T_att10db.setText(QCoreApplication.translate("Widget", u"10dB", None))
        self.groupBox_gain.setTitle(QCoreApplication.translate("Widget", u"\u589e\u76ca", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"\u57fa\u5e26\u589e\u76ca", None))
        self.comboBox_T_BBGain.setItemText(0, QCoreApplication.translate("Widget", u"-6dB", None))
        self.comboBox_T_BBGain.setItemText(1, QCoreApplication.translate("Widget", u"0dB", None))
        self.comboBox_T_BBGain.setItemText(2, QCoreApplication.translate("Widget", u"6dB", None))
        self.comboBox_T_BBGain.setItemText(3, QCoreApplication.translate("Widget", u"12dB", None))

        self.label_6.setText(QCoreApplication.translate("Widget", u"\u6ee4\u6ce2\u589e\u76ca", None))
        self.comboBox_T_filterGain.setItemText(0, QCoreApplication.translate("Widget", u"0dB", None))
        self.comboBox_T_filterGain.setItemText(1, QCoreApplication.translate("Widget", u"6dB", None))
        self.comboBox_T_filterGain.setItemText(2, QCoreApplication.translate("Widget", u"12dB", None))

        self.tabWidget_ctrl.setTabText(self.tabWidget_ctrl.indexOf(self.tab_tx), QCoreApplication.translate("Widget", u"Tx\u63a7\u5236", None))
        self.groupBox_ctrlRx.setTitle("")
        self.groupBox_IDAC_4.setTitle(QCoreApplication.translate("Widget", u"IDAC LB->1  HB->TIA", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"P", None))
        self.label_20.setText(QCoreApplication.translate("Widget", u"N", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"Q", None))
        self.label_22.setText(QCoreApplication.translate("Widget", u"I", None))
        self.groupBox_gain_4.setTitle(QCoreApplication.translate("Widget", u"\u589e\u76ca", None))
        self.label_23.setText(QCoreApplication.translate("Widget", u"\u57fa\u5e26\u589e\u76ca", None))
        self.comboBox_R_BBGain.setItemText(0, QCoreApplication.translate("Widget", u"-6dB", None))
        self.comboBox_R_BBGain.setItemText(1, QCoreApplication.translate("Widget", u"0dB", None))
        self.comboBox_R_BBGain.setItemText(2, QCoreApplication.translate("Widget", u"6dB", None))
        self.comboBox_R_BBGain.setItemText(3, QCoreApplication.translate("Widget", u"12dB", None))

        self.label_24.setText(QCoreApplication.translate("Widget", u"\u4e00\u7ea7\u6ee4\u6ce2\u589e\u76ca", None))
        self.comboBox_R_filterGain1.setItemText(0, QCoreApplication.translate("Widget", u"0dB", None))
        self.comboBox_R_filterGain1.setItemText(1, QCoreApplication.translate("Widget", u"6dB", None))
        self.comboBox_R_filterGain1.setItemText(2, QCoreApplication.translate("Widget", u"12dB", None))

        self.label_25.setText(QCoreApplication.translate("Widget", u"\u4e8c\u7ea7\u6ee4\u6ce2\u589e\u76ca", None))
        self.comboBox_R_filterGain2.setItemText(0, QCoreApplication.translate("Widget", u"0dB", None))
        self.comboBox_R_filterGain2.setItemText(1, QCoreApplication.translate("Widget", u"6dB", None))
        self.comboBox_R_filterGain2.setItemText(2, QCoreApplication.translate("Widget", u"12dB", None))

        self.label_30.setText(QCoreApplication.translate("Widget", u"TIA\u589e\u76ca", None))
        self.comboBox_R_TIAGain.setItemText(0, QCoreApplication.translate("Widget", u"30dB", None))
        self.comboBox_R_TIAGain.setItemText(1, QCoreApplication.translate("Widget", u"24dB", None))
        self.comboBox_R_TIAGain.setItemText(2, QCoreApplication.translate("Widget", u"18dB", None))

        self.groupBox_IDAC_5.setTitle(QCoreApplication.translate("Widget", u"IDAC LB->2  HB->FIL", None))
        self.label_26.setText(QCoreApplication.translate("Widget", u"P", None))
        self.label_27.setText(QCoreApplication.translate("Widget", u"N", None))
        self.label_28.setText(QCoreApplication.translate("Widget", u"Q", None))
        self.label_29.setText(QCoreApplication.translate("Widget", u"I", None))
        self.tabWidget_ctrl.setTabText(self.tabWidget_ctrl.indexOf(self.tab_rx), QCoreApplication.translate("Widget", u"Rx\u63a7\u5236", None))
        self.groupBox_BBBW.setTitle(QCoreApplication.translate("Widget", u"\u5e26\u5bbd", None))
        self.radioButton_BBBW100M.setText(QCoreApplication.translate("Widget", u"100M", None))
        self.radioButton_BBBW250M.setText(QCoreApplication.translate("Widget", u"250M", None))
        self.radioButton_BBBW500M.setText(QCoreApplication.translate("Widget", u"500M", None))
        self.pushButton_consoleClear.setText(QCoreApplication.translate("Widget", u"\u6e05\u7a7a", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Widget", u"\u63a5\u6536\u7aef", None))
        self.label_freq_4.setText(QCoreApplication.translate("Widget", u"\u63a5\u6536\u5230\u7684\u6587\u5b57\u6d88\u606f\uff1a", None))
        self.label_freq_5.setText(QCoreApplication.translate("Widget", u"\u63a5\u6536\u5230\u7684\u56fe\u50cf\uff1a", None))
        self.label_commImgR.setText(QCoreApplication.translate("Widget", u"pic", None))
        self.pushButton_commRunStop.setText(QCoreApplication.translate("Widget", u"\u542f\u52a8/\u505c\u6b62\u63a5\u6536", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Widget", u"\u53d1\u9001\u7aef", None))
        self.label_commImgT.setText(QCoreApplication.translate("Widget", u"pic", None))
        self.label_freq_6.setText(QCoreApplication.translate("Widget", u"\u8981\u53d1\u9001\u7684\u56fe\u50cf\uff1a", None))
        self.label_freq_7.setText(QCoreApplication.translate("Widget", u"\u8981\u53d1\u9001\u7684\u6587\u5b57\u6d88\u606f\uff1a", None))
        self.pushButton_commImgT.setText(QCoreApplication.translate("Widget", u"\u53d1\u9001\u56fe\u50cf", None))
        self.pushButton_commTextT.setText(QCoreApplication.translate("Widget", u"\u53d1\u9001\u6587\u5b57", None))
        self.pushButton_commImgSelect.setText(QCoreApplication.translate("Widget", u"\u9009\u62e9\u56fe\u50cf", None))
        self.radioButton_commR.setText(QCoreApplication.translate("Widget", u"\u5f53\u524d\u4e3a\u63a5\u6536\u6a21\u5f0f", None))
        self.radioButton_commT.setText(QCoreApplication.translate("Widget", u"\u5f53\u524d\u4e3a\u53d1\u9001\u6a21\u5f0f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_comm), QCoreApplication.translate("Widget", u"\u901a\u4fe1", None))
        self.pushButton_runStop.setText(QCoreApplication.translate("Widget", u"\u542f\u52a8/\u505c\u6b62", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_radar), QCoreApplication.translate("Widget", u"\u96f7\u8fbe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_adversarial), QCoreApplication.translate("Widget", u"\u5bf9\u6297", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Widget", u"debug", None))
        self.pushButton_rxConfigSend.setText(QCoreApplication.translate("Widget", u"RX\u914d\u7f6e\u53d1\u9001", None))
        self.pushButton_txConfigSend.setText(QCoreApplication.translate("Widget", u"TX\u914d\u7f6e\u53d1\u9001", None))
    # retranslateUi

