set_property -dict {PACKAGE_PIN AG15 IOSTANDARD LVDS} [get_ports pl_clk_p]
set_property -dict {PACKAGE_PIN AG17 IOSTANDARD LVDS} [get_ports pl_sysref_p]
set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33} [get_ports lmk_sync]
#set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
#set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
#set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports {led[2]}]

set_property PACKAGE_PIN E14 [get_ports CSN1P8_TX]
set_property PACKAGE_PIN H15 [get_ports MISO1P8_TX]
set_property PACKAGE_PIN K15 [get_ports MOSI1P8_TX]
set_property PACKAGE_PIN B13 [get_ports RESN1P8_TX]
set_property PACKAGE_PIN K14 [get_ports SCLK1P8_TX]
set_property IOSTANDARD LVCMOS18 [get_ports CSN1P8_TX]
set_property IOSTANDARD LVCMOS18 [get_ports MISO1P8_TX]
set_property IOSTANDARD LVCMOS18 [get_ports MOSI1P8_TX]
set_property IOSTANDARD LVCMOS18 [get_ports RESN1P8_TX]
set_property IOSTANDARD LVCMOS18 [get_ports SCLK1P8_TX]



set_property MARK_DEBUG true [get_nets {control_out[0]}]
set_property MARK_DEBUG true [get_nets {control_out[1]}]

set_property MARK_DEBUG false [get_nets {data_in[141]}]
set_property MARK_DEBUG false [get_nets {data_in[62]}]
set_property MARK_DEBUG false [get_nets {data_in[201]}]
set_property MARK_DEBUG false [get_nets {data_in[305]}]
set_property MARK_DEBUG false [get_nets {data_in[322]}]
set_property MARK_DEBUG false [get_nets {data_in[385]}]
set_property MARK_DEBUG false [get_nets {data_in[481]}]
set_property MARK_DEBUG false [get_nets {data_in[510]}]
set_property MARK_DEBUG false [get_nets {data_in[53]}]
set_property MARK_DEBUG false [get_nets {data_in[165]}]
set_property MARK_DEBUG false [get_nets {data_in[73]}]
set_property MARK_DEBUG false [get_nets {data_in[248]}]
set_property MARK_DEBUG false [get_nets {data_in[270]}]
set_property MARK_DEBUG false [get_nets {data_in[361]}]
set_property MARK_DEBUG false [get_nets {data_in[440]}]
set_property MARK_DEBUG false [get_nets {data_in[500]}]
set_property MARK_DEBUG false [get_nets {data_in[42]}]
set_property MARK_DEBUG false [get_nets {data_in[75]}]
set_property MARK_DEBUG false [get_nets {data_in[147]}]
set_property MARK_DEBUG false [get_nets {data_in[204]}]
set_property MARK_DEBUG false [get_nets {data_in[273]}]
set_property MARK_DEBUG false [get_nets {data_in[334]}]
set_property MARK_DEBUG false [get_nets {data_in[405]}]
set_property MARK_DEBUG false [get_nets {data_in[484]}]
set_property MARK_DEBUG false [get_nets {data_in[37]}]
set_property MARK_DEBUG false [get_nets {data_in[114]}]
set_property MARK_DEBUG false [get_nets {data_in[186]}]
set_property MARK_DEBUG false [get_nets {data_in[223]}]
set_property MARK_DEBUG false [get_nets {data_in[290]}]
set_property MARK_DEBUG false [get_nets {data_in[359]}]
set_property MARK_DEBUG false [get_nets {data_in[422]}]
set_property MARK_DEBUG false [get_nets {data_in[474]}]
set_property MARK_DEBUG false [get_nets {data_in[29]}]
set_property MARK_DEBUG false [get_nets {data_in[105]}]
set_property MARK_DEBUG false [get_nets {data_in[132]}]
set_property MARK_DEBUG false [get_nets {data_in[215]}]
set_property MARK_DEBUG false [get_nets {data_in[278]}]
set_property MARK_DEBUG false [get_nets {data_in[335]}]
set_property MARK_DEBUG false [get_nets {data_in[382]}]
set_property MARK_DEBUG false [get_nets {data_in[466]}]
set_property MARK_DEBUG false [get_nets {data_in[3]}]
set_property MARK_DEBUG false [get_nets {data_in[143]}]
set_property MARK_DEBUG false [get_nets {data_in[64]}]
set_property MARK_DEBUG false [get_nets {data_in[233]}]
set_property MARK_DEBUG false [get_nets {data_in[300]}]
set_property MARK_DEBUG false [get_nets {data_in[340]}]
set_property MARK_DEBUG false [get_nets {data_in[388]}]
set_property MARK_DEBUG false [get_nets {data_in[488]}]
set_property MARK_DEBUG false [get_nets {data_in[38]}]
set_property MARK_DEBUG false [get_nets {data_in[166]}]
set_property MARK_DEBUG false [get_nets {data_in[100]}]
set_property MARK_DEBUG false [get_nets {data_in[249]}]
set_property MARK_DEBUG false [get_nets {data_in[272]}]
set_property MARK_DEBUG false [get_nets {data_in[367]}]
set_property MARK_DEBUG false [get_nets {data_in[442]}]
set_property MARK_DEBUG false [get_nets {data_in[501]}]
set_property MARK_DEBUG false [get_nets {data_in[5]}]
set_property MARK_DEBUG false [get_nets {data_in[160]}]
set_property MARK_DEBUG false [get_nets {data_in[85]}]
set_property MARK_DEBUG false [get_nets {data_in[234]}]
set_property MARK_DEBUG false [get_nets {data_in[296]}]
set_property MARK_DEBUG false [get_nets {data_in[325]}]
set_property MARK_DEBUG false [get_nets {data_in[386]}]
set_property MARK_DEBUG false [get_nets {data_in[495]}]
set_property MARK_DEBUG false [get_nets {data_in[59]}]
set_property MARK_DEBUG false [get_nets {data_in[74]}]
set_property MARK_DEBUG false [get_nets {data_in[183]}]
set_property MARK_DEBUG false [get_nets {data_in[200]}]
set_property MARK_DEBUG false [get_nets {data_in[316]}]
set_property MARK_DEBUG false [get_nets {data_in[341]}]
set_property MARK_DEBUG false [get_nets {data_in[429]}]
set_property MARK_DEBUG false [get_nets {data_in[508]}]
set_property MARK_DEBUG false [get_nets {data_in[1]}]
set_property MARK_DEBUG false [get_nets {data_in[109]}]
set_property MARK_DEBUG false [get_nets {data_in[173]}]
set_property MARK_DEBUG false [get_nets {data_in[203]}]
set_property MARK_DEBUG false [get_nets {data_in[257]}]
set_property MARK_DEBUG false [get_nets {data_in[371]}]
set_property MARK_DEBUG false [get_nets {data_in[401]}]
set_property MARK_DEBUG false [get_nets {data_in[446]}]
set_property MARK_DEBUG false [get_nets {data_in[22]}]
set_property MARK_DEBUG false [get_nets {data_in[123]}]
set_property MARK_DEBUG false [get_nets {data_in[157]}]
set_property MARK_DEBUG false [get_nets {data_in[238]}]
set_property MARK_DEBUG false [get_nets {data_in[277]}]
set_property MARK_DEBUG false [get_nets {data_in[330]}]
set_property MARK_DEBUG false [get_nets {data_in[411]}]
set_property MARK_DEBUG false [get_nets {data_in[467]}]
set_property MARK_DEBUG false [get_nets {data_in[21]}]
set_property MARK_DEBUG false [get_nets {data_in[180]}]
set_property MARK_DEBUG false [get_nets {data_in[103]}]
set_property MARK_DEBUG false [get_nets {data_in[225]}]
set_property MARK_DEBUG false [get_nets {data_in[309]}]
set_property MARK_DEBUG false [get_nets {data_in[365]}]
set_property MARK_DEBUG false [get_nets {data_in[426]}]
set_property MARK_DEBUG false [get_nets {data_in[497]}]
set_property MARK_DEBUG false [get_nets {data_in[52]}]
set_property MARK_DEBUG false [get_nets {data_in[163]}]
set_property MARK_DEBUG false [get_nets {data_in[96]}]
set_property MARK_DEBUG false [get_nets {data_in[246]}]
set_property MARK_DEBUG false [get_nets {data_in[261]}]
set_property MARK_DEBUG false [get_nets {data_in[357]}]
set_property MARK_DEBUG false [get_nets {data_in[420]}]
set_property MARK_DEBUG false [get_nets {data_in[476]}]
set_property MARK_DEBUG false [get_nets {data_in[60]}]
set_property MARK_DEBUG false [get_nets {data_in[77]}]
set_property MARK_DEBUG false [get_nets {data_in[184]}]
set_property MARK_DEBUG false [get_nets {data_in[230]}]
set_property MARK_DEBUG false [get_nets {data_in[317]}]
set_property MARK_DEBUG false [get_nets {data_in[332]}]
set_property MARK_DEBUG false [get_nets {data_in[441]}]
set_property MARK_DEBUG false [get_nets {data_in[509]}]
set_property MARK_DEBUG false [get_nets {data_in[7]}]
set_property MARK_DEBUG false [get_nets {data_in[112]}]
set_property MARK_DEBUG false [get_nets {data_in[142]}]
set_property MARK_DEBUG false [get_nets {data_in[205]}]
set_property MARK_DEBUG false [get_nets {data_in[286]}]
set_property MARK_DEBUG false [get_nets {data_in[356]}]
set_property MARK_DEBUG false [get_nets {data_in[418]}]
set_property MARK_DEBUG false [get_nets {data_in[455]}]
set_property MARK_DEBUG false [get_nets {data_in[27]}]
set_property MARK_DEBUG false [get_nets {data_in[121]}]
set_property MARK_DEBUG false [get_nets {data_in[139]}]
set_property MARK_DEBUG false [get_nets {data_in[222]}]
set_property MARK_DEBUG false [get_nets {data_in[279]}]
set_property MARK_DEBUG false [get_nets {data_in[333]}]
set_property MARK_DEBUG false [get_nets {data_in[434]}]
set_property MARK_DEBUG false [get_nets {data_in[496]}]
set_property MARK_DEBUG false [get_nets {data_in[49]}]
set_property MARK_DEBUG false [get_nets {data_in[88]}]
set_property MARK_DEBUG false [get_nets {data_in[251]}]
set_property MARK_DEBUG false [get_nets {data_in[156]}]
set_property MARK_DEBUG false [get_nets {data_in[280]}]
set_property MARK_DEBUG false [get_nets {data_in[370]}]
set_property MARK_DEBUG false [get_nets {data_in[412]}]
set_property MARK_DEBUG false [get_nets {data_in[468]}]
set_property MARK_DEBUG false [get_nets {data_in[31]}]
set_property MARK_DEBUG false [get_nets {data_in[90]}]
set_property MARK_DEBUG false [get_nets {data_in[151]}]
set_property MARK_DEBUG false [get_nets {data_in[252]}]
set_property MARK_DEBUG false [get_nets {data_in[301]}]
set_property MARK_DEBUG false [get_nets {data_in[344]}]
set_property MARK_DEBUG false [get_nets {data_in[443]}]
set_property MARK_DEBUG false [get_nets {data_in[489]}]
set_property MARK_DEBUG false [get_nets {data_in[17]}]
set_property MARK_DEBUG false [get_nets {data_in[70]}]
set_property MARK_DEBUG false [get_nets {data_in[168]}]
set_property MARK_DEBUG false [get_nets {data_in[227]}]
set_property MARK_DEBUG false [get_nets {data_in[259]}]
set_property MARK_DEBUG false [get_nets {data_in[358]}]
set_property MARK_DEBUG false [get_nets {data_in[394]}]
set_property MARK_DEBUG false [get_nets {data_in[457]}]
set_property MARK_DEBUG false [get_nets {data_in[24]}]
set_property MARK_DEBUG false [get_nets {data_in[124]}]
set_property MARK_DEBUG false [get_nets {data_in[128]}]
set_property MARK_DEBUG false [get_nets {data_in[211]}]
set_property MARK_DEBUG false [get_nets {data_in[281]}]
set_property MARK_DEBUG false [get_nets {data_in[318]}]
set_property MARK_DEBUG false [get_nets {data_in[410]}]
set_property MARK_DEBUG false [get_nets {data_in[462]}]
set_property MARK_DEBUG false [get_nets {data_in[46]}]
set_property MARK_DEBUG false [get_nets {data_in[158]}]
set_property MARK_DEBUG false [get_nets {data_in[76]}]
set_property MARK_DEBUG false [get_nets {data_in[244]}]
set_property MARK_DEBUG false [get_nets {data_in[310]}]
set_property MARK_DEBUG false [get_nets {data_in[349]}]
set_property MARK_DEBUG false [get_nets {data_in[430]}]
set_property MARK_DEBUG false [get_nets {data_in[472]}]
set_property MARK_DEBUG false [get_nets {data_in[54]}]
set_property MARK_DEBUG false [get_nets {data_in[79]}]
set_property MARK_DEBUG false [get_nets {data_in[206]}]
set_property MARK_DEBUG false [get_nets {data_in[154]}]
set_property MARK_DEBUG false [get_nets {data_in[299]}]
set_property MARK_DEBUG false [get_nets {data_in[373]}]
set_property MARK_DEBUG false [get_nets {data_in[435]}]
set_property MARK_DEBUG false [get_nets {data_in[487]}]
set_property MARK_DEBUG false [get_nets {data_in[61]}]
set_property MARK_DEBUG false [get_nets {data_in[97]}]
set_property MARK_DEBUG false [get_nets {data_in[150]}]
set_property MARK_DEBUG false [get_nets {data_in[253]}]
set_property MARK_DEBUG false [get_nets {data_in[307]}]
set_property MARK_DEBUG false [get_nets {data_in[343]}]
set_property MARK_DEBUG false [get_nets {data_in[445]}]
set_property MARK_DEBUG false [get_nets {data_in[498]}]
set_property MARK_DEBUG false [get_nets {data_in[34]}]
set_property MARK_DEBUG false [get_nets {data_in[117]}]
set_property MARK_DEBUG false [get_nets {data_in[188]}]
set_property MARK_DEBUG false [get_nets {data_in[231]}]
set_property MARK_DEBUG false [get_nets {data_in[268]}]
set_property MARK_DEBUG false [get_nets {data_in[379]}]
set_property MARK_DEBUG false [get_nets {data_in[402]}]
set_property MARK_DEBUG false [get_nets {data_in[486]}]
set_property MARK_DEBUG false [get_nets {data_in[39]}]
set_property MARK_DEBUG false [get_nets {data_in[115]}]
set_property MARK_DEBUG false [get_nets {data_in[187]}]
set_property MARK_DEBUG false [get_nets {data_in[226]}]
set_property MARK_DEBUG false [get_nets {data_in[283]}]
set_property MARK_DEBUG false [get_nets {data_in[377]}]
set_property MARK_DEBUG false [get_nets {data_in[415]}]
set_property MARK_DEBUG false [get_nets {data_in[471]}]
set_property MARK_DEBUG false [get_nets {data_in[12]}]
set_property MARK_DEBUG false [get_nets {data_in[98]}]
set_property MARK_DEBUG false [get_nets {data_in[136]}]
set_property MARK_DEBUG false [get_nets {data_in[219]}]
set_property MARK_DEBUG false [get_nets {data_in[274]}]
set_property MARK_DEBUG false [get_nets {data_in[328]}]
set_property MARK_DEBUG false [get_nets {data_in[406]}]
set_property MARK_DEBUG false [get_nets {data_in[450]}]
set_property MARK_DEBUG false [get_nets {data_in[19]}]
set_property MARK_DEBUG false [get_nets {data_in[145]}]
set_property MARK_DEBUG false [get_nets {data_in[71]}]
set_property MARK_DEBUG false [get_nets {data_in[241]}]
set_property MARK_DEBUG false [get_nets {data_in[284]}]
set_property MARK_DEBUG false [get_nets {data_in[342]}]
set_property MARK_DEBUG false [get_nets {data_in[416]}]
set_property MARK_DEBUG false [get_nets {data_in[448]}]
set_property MARK_DEBUG false [get_nets {data_in[40]}]
set_property MARK_DEBUG false [get_nets {data_in[101]}]
set_property MARK_DEBUG false [get_nets {data_in[250]}]
set_property MARK_DEBUG false [get_nets {data_in[172]}]
set_property MARK_DEBUG false [get_nets {data_in[288]}]
set_property MARK_DEBUG false [get_nets {data_in[368]}]
set_property MARK_DEBUG false [get_nets {data_in[444]}]
set_property MARK_DEBUG false [get_nets {data_in[502]}]
set_property MARK_DEBUG false [get_nets {data_in[9]}]
set_property MARK_DEBUG false [get_nets {data_in[84]}]
set_property MARK_DEBUG false [get_nets {data_in[185]}]
set_property MARK_DEBUG false [get_nets {data_in[245]}]
set_property MARK_DEBUG false [get_nets {data_in[295]}]
set_property MARK_DEBUG false [get_nets {data_in[360]}]
set_property MARK_DEBUG false [get_nets {data_in[433]}]
set_property MARK_DEBUG false [get_nets {data_in[483]}]
set_property MARK_DEBUG false [get_nets {data_in[23]}]
set_property MARK_DEBUG false [get_nets {data_in[116]}]
set_property MARK_DEBUG false [get_nets {data_in[182]}]
set_property MARK_DEBUG false [get_nets {data_in[228]}]
set_property MARK_DEBUG false [get_nets {data_in[298]}]
set_property MARK_DEBUG false [get_nets {data_in[378]}]
set_property MARK_DEBUG false [get_nets {data_in[431]}]
set_property MARK_DEBUG false [get_nets {data_in[449]}]
set_property MARK_DEBUG false [get_nets {data_in[2]}]
set_property MARK_DEBUG false [get_nets {data_in[86]}]
set_property MARK_DEBUG false [get_nets {data_in[148]}]
set_property MARK_DEBUG false [get_nets {data_in[197]}]
set_property MARK_DEBUG false [get_nets {data_in[276]}]
set_property MARK_DEBUG false [get_nets {data_in[336]}]
set_property MARK_DEBUG false [get_nets {data_in[408]}]
set_property MARK_DEBUG false [get_nets {data_in[460]}]
set_property MARK_DEBUG false [get_nets {data_in[28]}]
set_property MARK_DEBUG false [get_nets {data_in[146]}]
set_property MARK_DEBUG false [get_nets {data_in[82]}]
set_property MARK_DEBUG false [get_nets {data_in[242]}]
set_property MARK_DEBUG false [get_nets {data_in[306]}]
set_property MARK_DEBUG false [get_nets {data_in[329]}]
set_property MARK_DEBUG false [get_nets {data_in[392]}]
set_property MARK_DEBUG false [get_nets {data_in[461]}]
set_property MARK_DEBUG false [get_nets {data_in[30]}]
set_property MARK_DEBUG false [get_nets {data_in[63]}]
set_property MARK_DEBUG false [get_nets {data_in[140]}]
set_property MARK_DEBUG false [get_nets {data_in[209]}]
set_property MARK_DEBUG false [get_nets {data_in[260]}]
set_property MARK_DEBUG false [get_nets {data_in[324]}]
set_property MARK_DEBUG false [get_nets {data_in[407]}]
set_property MARK_DEBUG false [get_nets {data_in[463]}]
set_property MARK_DEBUG false [get_nets {data_in[58]}]
set_property MARK_DEBUG false [get_nets {data_in[120]}]
set_property MARK_DEBUG false [get_nets {data_in[189]}]
set_property MARK_DEBUG false [get_nets {data_in[235]}]
set_property MARK_DEBUG false [get_nets {data_in[303]}]
set_property MARK_DEBUG false [get_nets {data_in[319]}]
set_property MARK_DEBUG false [get_nets {data_in[432]}]
set_property MARK_DEBUG false [get_nets {data_in[491]}]
set_property MARK_DEBUG false [get_nets {data_in[36]}]
set_property MARK_DEBUG false [get_nets {data_in[149]}]
set_property MARK_DEBUG false [get_nets {data_in[99]}]
set_property MARK_DEBUG false [get_nets {data_in[224]}]
set_property MARK_DEBUG false [get_nets {data_in[282]}]
set_property MARK_DEBUG false [get_nets {data_in[347]}]
set_property MARK_DEBUG false [get_nets {data_in[384]}]
set_property MARK_DEBUG false [get_nets {data_in[470]}]
set_property MARK_DEBUG false [get_nets {data_in[48]}]
set_property MARK_DEBUG false [get_nets {data_in[133]}]
set_property MARK_DEBUG false [get_nets {data_in[93]}]
set_property MARK_DEBUG false [get_nets {data_in[216]}]
set_property MARK_DEBUG false [get_nets {data_in[304]}]
set_property MARK_DEBUG false [get_nets {data_in[320]}]
set_property MARK_DEBUG false [get_nets {data_in[437]}]
set_property MARK_DEBUG false [get_nets {data_in[492]}]
set_property MARK_DEBUG false [get_nets {data_in[13]}]
set_property MARK_DEBUG false [get_nets {data_in[106]}]
set_property MARK_DEBUG false [get_nets {data_in[229]}]
set_property MARK_DEBUG false [get_nets {data_in[169]}]
set_property MARK_DEBUG false [get_nets {data_in[266]}]
set_property MARK_DEBUG false [get_nets {data_in[369]}]
set_property MARK_DEBUG false [get_nets {data_in[395]}]
set_property MARK_DEBUG false [get_nets {data_in[504]}]
set_property MARK_DEBUG false [get_nets {data_in[44]}]
set_property MARK_DEBUG false [get_nets {data_in[83]}]
set_property MARK_DEBUG false [get_nets {data_in[177]}]
set_property MARK_DEBUG false [get_nets {data_in[190]}]
set_property MARK_DEBUG false [get_nets {data_in[275]}]
set_property MARK_DEBUG false [get_nets {data_in[354]}]
set_property MARK_DEBUG false [get_nets {data_in[419]}]
set_property MARK_DEBUG false [get_nets {data_in[475]}]
set_property MARK_DEBUG false [get_nets {data_in[6]}]
set_property MARK_DEBUG false [get_nets {data_in[110]}]
set_property MARK_DEBUG false [get_nets {data_in[129]}]
set_property MARK_DEBUG false [get_nets {data_in[196]}]
set_property MARK_DEBUG false [get_nets {data_in[269]}]
set_property MARK_DEBUG false [get_nets {data_in[380]}]
set_property MARK_DEBUG false [get_nets {data_in[387]}]
set_property MARK_DEBUG false [get_nets {data_in[465]}]
set_property MARK_DEBUG false [get_nets {data_in[41]}]
set_property MARK_DEBUG false [get_nets {data_in[170]}]
set_property MARK_DEBUG false [get_nets {data_in[107]}]
set_property MARK_DEBUG false [get_nets {data_in[192]}]
set_property MARK_DEBUG false [get_nets {data_in[289]}]
set_property MARK_DEBUG false [get_nets {data_in[353]}]
set_property MARK_DEBUG false [get_nets {data_in[414]}]
set_property MARK_DEBUG false [get_nets {data_in[477]}]
set_property MARK_DEBUG false [get_nets {data_in[14]}]
set_property MARK_DEBUG false [get_nets {data_in[161]}]
set_property MARK_DEBUG false [get_nets {data_in[68]}]
set_property MARK_DEBUG false [get_nets {data_in[239]}]
set_property MARK_DEBUG false [get_nets {data_in[293]}]
set_property MARK_DEBUG false [get_nets {data_in[337]}]
set_property MARK_DEBUG false [get_nets {data_in[396]}]
set_property MARK_DEBUG false [get_nets {data_in[464]}]
set_property MARK_DEBUG false [get_nets {data_in[47]}]
set_property MARK_DEBUG false [get_nets {data_in[162]}]
set_property MARK_DEBUG false [get_nets {data_in[89]}]
set_property MARK_DEBUG false [get_nets {data_in[247]}]
set_property MARK_DEBUG false [get_nets {data_in[311]}]
set_property MARK_DEBUG false [get_nets {data_in[350]}]
set_property MARK_DEBUG false [get_nets {data_in[436]}]
set_property MARK_DEBUG false [get_nets {data_in[493]}]
set_property MARK_DEBUG false [get_nets {data_in[55]}]
set_property MARK_DEBUG false [get_nets {data_in[67]}]
set_property MARK_DEBUG false [get_nets {data_in[207]}]
set_property MARK_DEBUG false [get_nets {data_in[174]}]
set_property MARK_DEBUG false [get_nets {data_in[264]}]
set_property MARK_DEBUG false [get_nets {data_in[364]}]
set_property MARK_DEBUG false [get_nets {data_in[398]}]
set_property MARK_DEBUG false [get_nets {data_in[503]}]
set_property MARK_DEBUG false [get_nets {data_in[26]}]
set_property MARK_DEBUG false [get_nets {data_in[69]}]
set_property MARK_DEBUG false [get_nets {data_in[126]}]
set_property MARK_DEBUG false [get_nets {data_in[198]}]
set_property MARK_DEBUG false [get_nets {data_in[254]}]
set_property MARK_DEBUG false [get_nets {data_in[345]}]
set_property MARK_DEBUG false [get_nets {data_in[427]}]
set_property MARK_DEBUG false [get_nets {data_in[452]}]
set_property MARK_DEBUG false [get_nets {data_in[4]}]
set_property MARK_DEBUG false [get_nets {data_in[118]}]
set_property MARK_DEBUG false [get_nets {data_in[159]}]
set_property MARK_DEBUG false [get_nets {data_in[232]}]
set_property MARK_DEBUG false [get_nets {data_in[285]}]
set_property MARK_DEBUG false [get_nets {data_in[321]}]
set_property MARK_DEBUG false [get_nets {data_in[417]}]
set_property MARK_DEBUG false [get_nets {data_in[473]}]
set_property MARK_DEBUG false [get_nets {data_in[33]}]
set_property MARK_DEBUG false [get_nets {data_in[127]}]
set_property MARK_DEBUG false [get_nets {data_in[65]}]
set_property MARK_DEBUG false [get_nets {data_in[210]}]
set_property MARK_DEBUG false [get_nets {data_in[263]}]
set_property MARK_DEBUG false [get_nets {data_in[339]}]
set_property MARK_DEBUG false [get_nets {data_in[413]}]
set_property MARK_DEBUG false [get_nets {data_in[469]}]
set_property MARK_DEBUG false [get_nets {data_in[32]}]
set_property MARK_DEBUG false [get_nets {data_in[130]}]
set_property MARK_DEBUG false [get_nets {data_in[81]}]
set_property MARK_DEBUG false [get_nets {data_in[213]}]
set_property MARK_DEBUG false [get_nets {data_in[312]}]
set_property MARK_DEBUG false [get_nets {data_in[351]}]
set_property MARK_DEBUG false [get_nets {data_in[383]}]
set_property MARK_DEBUG false [get_nets {data_in[480]}]
set_property MARK_DEBUG false [get_nets {data_in[56]}]
set_property MARK_DEBUG false [get_nets {data_in[91]}]
set_property MARK_DEBUG false [get_nets {data_in[237]}]
set_property MARK_DEBUG false [get_nets {data_in[176]}]
set_property MARK_DEBUG false [get_nets {data_in[302]}]
set_property MARK_DEBUG false [get_nets {data_in[338]}]
set_property MARK_DEBUG false [get_nets {data_in[438]}]
set_property MARK_DEBUG false [get_nets {data_in[490]}]
set_property MARK_DEBUG false [get_nets {data_in[11]}]
set_property MARK_DEBUG false [get_nets {data_in[78]}]
set_property MARK_DEBUG false [get_nets {data_in[153]}]
set_property MARK_DEBUG false [get_nets {data_in[236]}]
set_property MARK_DEBUG false [get_nets {data_in[255]}]
set_property MARK_DEBUG false [get_nets {data_in[374]}]
set_property MARK_DEBUG false [get_nets {data_in[409]}]
set_property MARK_DEBUG false [get_nets {data_in[453]}]
set_property MARK_DEBUG false [get_nets {data_in[43]}]
set_property MARK_DEBUG false [get_nets {data_in[175]}]
set_property MARK_DEBUG false [get_nets {data_in[125]}]
set_property MARK_DEBUG false [get_nets {data_in[194]}]
set_property MARK_DEBUG false [get_nets {data_in[291]}]
set_property MARK_DEBUG false [get_nets {data_in[346]}]
set_property MARK_DEBUG false [get_nets {data_in[423]}]
set_property MARK_DEBUG false [get_nets {data_in[479]}]
set_property MARK_DEBUG false [get_nets {data_in[8]}]
set_property MARK_DEBUG false [get_nets {data_in[138]}]
set_property MARK_DEBUG false [get_nets {data_in[95]}]
set_property MARK_DEBUG false [get_nets {data_in[221]}]
set_property MARK_DEBUG false [get_nets {data_in[258]}]
set_property MARK_DEBUG false [get_nets {data_in[348]}]
set_property MARK_DEBUG false [get_nets {data_in[404]}]
set_property MARK_DEBUG false [get_nets {data_in[456]}]
set_property MARK_DEBUG false [get_nets {data_in[35]}]
set_property MARK_DEBUG false [get_nets {data_in[111]}]
set_property MARK_DEBUG false [get_nets {data_in[195]}]
set_property MARK_DEBUG false [get_nets {data_in[181]}]
set_property MARK_DEBUG false [get_nets {data_in[292]}]
set_property MARK_DEBUG false [get_nets {data_in[376]}]
set_property MARK_DEBUG false [get_nets {data_in[424]}]
set_property MARK_DEBUG false [get_nets {data_in[507]}]
set_property MARK_DEBUG false [get_nets {data_in[16]}]
set_property MARK_DEBUG false [get_nets {data_in[66]}]
set_property MARK_DEBUG false [get_nets {data_in[167]}]
set_property MARK_DEBUG false [get_nets {data_in[193]}]
set_property MARK_DEBUG false [get_nets {data_in[267]}]
set_property MARK_DEBUG false [get_nets {data_in[363]}]
set_property MARK_DEBUG false [get_nets {data_in[393]}]
set_property MARK_DEBUG false [get_nets {data_in[478]}]
set_property MARK_DEBUG false [get_nets {data_in[18]}]
set_property MARK_DEBUG false [get_nets {data_in[122]}]
set_property MARK_DEBUG false [get_nets {data_in[131]}]
set_property MARK_DEBUG false [get_nets {data_in[214]}]
set_property MARK_DEBUG false [get_nets {data_in[271]}]
set_property MARK_DEBUG false [get_nets {data_in[381]}]
set_property MARK_DEBUG false [get_nets {data_in[425]}]
set_property MARK_DEBUG false [get_nets {data_in[499]}]
set_property MARK_DEBUG false [get_nets {data_in[45]}]
set_property MARK_DEBUG false [get_nets {data_in[164]}]
set_property MARK_DEBUG false [get_nets {data_in[113]}]
set_property MARK_DEBUG false [get_nets {data_in[218]}]
set_property MARK_DEBUG false [get_nets {data_in[308]}]
set_property MARK_DEBUG false [get_nets {data_in[362]}]
set_property MARK_DEBUG false [get_nets {data_in[390]}]
set_property MARK_DEBUG false [get_nets {data_in[485]}]
set_property MARK_DEBUG false [get_nets {data_in[51]}]
set_property MARK_DEBUG false [get_nets {data_in[144]}]
set_property MARK_DEBUG false [get_nets {data_in[80]}]
set_property MARK_DEBUG false [get_nets {data_in[191]}]
set_property MARK_DEBUG false [get_nets {data_in[256]}]
set_property MARK_DEBUG false [get_nets {data_in[355]}]
set_property MARK_DEBUG false [get_nets {data_in[389]}]
set_property MARK_DEBUG false [get_nets {data_in[454]}]
set_property MARK_DEBUG false [get_nets {data_in[25]}]
set_property MARK_DEBUG false [get_nets {data_in[134]}]
set_property MARK_DEBUG false [get_nets {data_in[94]}]
set_property MARK_DEBUG false [get_nets {data_in[217]}]
set_property MARK_DEBUG false [get_nets {data_in[313]}]
set_property MARK_DEBUG false [get_nets {data_in[352]}]
set_property MARK_DEBUG false [get_nets {data_in[439]}]
set_property MARK_DEBUG false [get_nets {data_in[451]}]
set_property MARK_DEBUG false [get_nets {data_in[102]}]
set_property MARK_DEBUG false [get_nets {data_in[240]}]
set_property MARK_DEBUG false [get_nets {data_in[178]}]
set_property MARK_DEBUG false [get_nets {data_in[265]}]
set_property MARK_DEBUG false [get_nets {data_in[375]}]
set_property MARK_DEBUG false [get_nets {data_in[399]}]
set_property MARK_DEBUG false [get_nets {data_in[505]}]
set_property MARK_DEBUG false [get_nets {data_in[57]}]
set_property MARK_DEBUG false [get_nets {data_in[87]}]
set_property MARK_DEBUG false [get_nets {data_in[179]}]
set_property MARK_DEBUG false [get_nets {data_in[199]}]
set_property MARK_DEBUG false [get_nets {data_in[287]}]
set_property MARK_DEBUG false [get_nets {data_in[366]}]
set_property MARK_DEBUG false [get_nets {data_in[428]}]
set_property MARK_DEBUG false [get_nets {data_in[482]}]
set_property MARK_DEBUG false [get_nets {data_in[0]}]
set_property MARK_DEBUG false [get_nets {data_in[104]}]
set_property MARK_DEBUG false [get_nets {data_in[152]}]
set_property MARK_DEBUG false [get_nets {data_in[212]}]
set_property MARK_DEBUG false [get_nets {data_in[262]}]
set_property MARK_DEBUG false [get_nets {data_in[323]}]
set_property MARK_DEBUG false [get_nets {data_in[403]}]
set_property MARK_DEBUG false [get_nets {data_in[447]}]
set_property MARK_DEBUG false [get_nets {data_in[511]}]
set_property MARK_DEBUG false [get_nets {data_in[10]}]
set_property MARK_DEBUG false [get_nets {data_in[135]}]
set_property MARK_DEBUG false [get_nets {data_in[119]}]
set_property MARK_DEBUG false [get_nets {data_in[208]}]
set_property MARK_DEBUG false [get_nets {data_in[297]}]
set_property MARK_DEBUG false [get_nets {data_in[326]}]
set_property MARK_DEBUG false [get_nets {data_in[421]}]
set_property MARK_DEBUG false [get_nets {data_in[458]}]
set_property MARK_DEBUG false [get_nets {data_in[50]}]
set_property MARK_DEBUG false [get_nets {data_in[137]}]
set_property MARK_DEBUG false [get_nets {data_in[72]}]
set_property MARK_DEBUG false [get_nets {data_in[220]}]
set_property MARK_DEBUG false [get_nets {data_in[314]}]
set_property MARK_DEBUG false [get_nets {data_in[331]}]
set_property MARK_DEBUG false [get_nets {data_in[391]}]
set_property MARK_DEBUG false [get_nets {data_in[494]}]
set_property MARK_DEBUG false [get_nets {data_in[20]}]
set_property MARK_DEBUG false [get_nets {data_in[108]}]
set_property MARK_DEBUG false [get_nets {data_in[243]}]
set_property MARK_DEBUG false [get_nets {data_in[155]}]
set_property MARK_DEBUG false [get_nets {data_in[315]}]
set_property MARK_DEBUG false [get_nets {data_in[372]}]
set_property MARK_DEBUG false [get_nets {data_in[400]}]
set_property MARK_DEBUG false [get_nets {data_in[506]}]
set_property MARK_DEBUG false [get_nets {data_in[15]}]
set_property MARK_DEBUG false [get_nets {data_in[92]}]
set_property MARK_DEBUG false [get_nets {data_in[171]}]
set_property MARK_DEBUG false [get_nets {data_in[202]}]
set_property MARK_DEBUG false [get_nets {data_in[294]}]
set_property MARK_DEBUG false [get_nets {data_in[327]}]
set_property MARK_DEBUG false [get_nets {data_in[397]}]
set_property MARK_DEBUG false [get_nets {data_in[459]}]
set_property MARK_DEBUG false [get_nets {control_in[0]}]
set_property MARK_DEBUG false [get_nets {control_in[1]}]
set_property MARK_DEBUG false [get_nets n_0_0]
set_property MARK_DEBUG false [get_nets n_0_1]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/usp_rf_data_converter_0/inst/i_system_usp_rf_data_converter_0_0_bufg_gt_ctrl/clk_adc0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {adc_data_i_ch4[0]} {adc_data_i_ch4[1]} {adc_data_i_ch4[2]} {adc_data_i_ch4[3]} {adc_data_i_ch4[4]} {adc_data_i_ch4[5]} {adc_data_i_ch4[6]} {adc_data_i_ch4[7]} {adc_data_i_ch4[8]} {adc_data_i_ch4[9]} {adc_data_i_ch4[10]} {adc_data_i_ch4[11]} {adc_data_i_ch4[12]} {adc_data_i_ch4[13]} {adc_data_i_ch4[14]} {adc_data_i_ch4[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {adc_data_i_ch5[0]} {adc_data_i_ch5[1]} {adc_data_i_ch5[2]} {adc_data_i_ch5[3]} {adc_data_i_ch5[4]} {adc_data_i_ch5[5]} {adc_data_i_ch5[6]} {adc_data_i_ch5[7]} {adc_data_i_ch5[8]} {adc_data_i_ch5[9]} {adc_data_i_ch5[10]} {adc_data_i_ch5[11]} {adc_data_i_ch5[12]} {adc_data_i_ch5[13]} {adc_data_i_ch5[14]} {adc_data_i_ch5[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {adc_data_i_ch6[0]} {adc_data_i_ch6[1]} {adc_data_i_ch6[2]} {adc_data_i_ch6[3]} {adc_data_i_ch6[4]} {adc_data_i_ch6[5]} {adc_data_i_ch6[6]} {adc_data_i_ch6[7]} {adc_data_i_ch6[8]} {adc_data_i_ch6[9]} {adc_data_i_ch6[10]} {adc_data_i_ch6[11]} {adc_data_i_ch6[12]} {adc_data_i_ch6[13]} {adc_data_i_ch6[14]} {adc_data_i_ch6[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {adc_data_i_ch7[0]} {adc_data_i_ch7[1]} {adc_data_i_ch7[2]} {adc_data_i_ch7[3]} {adc_data_i_ch7[4]} {adc_data_i_ch7[5]} {adc_data_i_ch7[6]} {adc_data_i_ch7[7]} {adc_data_i_ch7[8]} {adc_data_i_ch7[9]} {adc_data_i_ch7[10]} {adc_data_i_ch7[11]} {adc_data_i_ch7[12]} {adc_data_i_ch7[13]} {adc_data_i_ch7[14]} {adc_data_i_ch7[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {adc_data_i_ch8[0]} {adc_data_i_ch8[1]} {adc_data_i_ch8[2]} {adc_data_i_ch8[3]} {adc_data_i_ch8[4]} {adc_data_i_ch8[5]} {adc_data_i_ch8[6]} {adc_data_i_ch8[7]} {adc_data_i_ch8[8]} {adc_data_i_ch8[9]} {adc_data_i_ch8[10]} {adc_data_i_ch8[11]} {adc_data_i_ch8[12]} {adc_data_i_ch8[13]} {adc_data_i_ch8[14]} {adc_data_i_ch8[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {adc_data_i_ch1[0]} {adc_data_i_ch1[1]} {adc_data_i_ch1[2]} {adc_data_i_ch1[3]} {adc_data_i_ch1[4]} {adc_data_i_ch1[5]} {adc_data_i_ch1[6]} {adc_data_i_ch1[7]} {adc_data_i_ch1[8]} {adc_data_i_ch1[9]} {adc_data_i_ch1[10]} {adc_data_i_ch1[11]} {adc_data_i_ch1[12]} {adc_data_i_ch1[13]} {adc_data_i_ch1[14]} {adc_data_i_ch1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {adc_data_i_ch2[0]} {adc_data_i_ch2[1]} {adc_data_i_ch2[2]} {adc_data_i_ch2[3]} {adc_data_i_ch2[4]} {adc_data_i_ch2[5]} {adc_data_i_ch2[6]} {adc_data_i_ch2[7]} {adc_data_i_ch2[8]} {adc_data_i_ch2[9]} {adc_data_i_ch2[10]} {adc_data_i_ch2[11]} {adc_data_i_ch2[12]} {adc_data_i_ch2[13]} {adc_data_i_ch2[14]} {adc_data_i_ch2[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {adc_data_i_ch3[0]} {adc_data_i_ch3[1]} {adc_data_i_ch3[2]} {adc_data_i_ch3[3]} {adc_data_i_ch3[4]} {adc_data_i_ch3[5]} {adc_data_i_ch3[6]} {adc_data_i_ch3[7]} {adc_data_i_ch3[8]} {adc_data_i_ch3[9]} {adc_data_i_ch3[10]} {adc_data_i_ch3[11]} {adc_data_i_ch3[12]} {adc_data_i_ch3[13]} {adc_data_i_ch3[14]} {adc_data_i_ch3[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {dac_data_i_ch4[0]} {dac_data_i_ch4[1]} {dac_data_i_ch4[2]} {dac_data_i_ch4[3]} {dac_data_i_ch4[4]} {dac_data_i_ch4[5]} {dac_data_i_ch4[6]} {dac_data_i_ch4[7]} {dac_data_i_ch4[8]} {dac_data_i_ch4[9]} {dac_data_i_ch4[10]} {dac_data_i_ch4[11]} {dac_data_i_ch4[12]} {dac_data_i_ch4[13]} {dac_data_i_ch4[14]} {dac_data_i_ch4[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 16 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {dac_data_q_ch8[0]} {dac_data_q_ch8[1]} {dac_data_q_ch8[2]} {dac_data_q_ch8[3]} {dac_data_q_ch8[4]} {dac_data_q_ch8[5]} {dac_data_q_ch8[6]} {dac_data_q_ch8[7]} {dac_data_q_ch8[8]} {dac_data_q_ch8[9]} {dac_data_q_ch8[10]} {dac_data_q_ch8[11]} {dac_data_q_ch8[12]} {dac_data_q_ch8[13]} {dac_data_q_ch8[14]} {dac_data_q_ch8[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {adc_data_q_ch4[0]} {adc_data_q_ch4[1]} {adc_data_q_ch4[2]} {adc_data_q_ch4[3]} {adc_data_q_ch4[4]} {adc_data_q_ch4[5]} {adc_data_q_ch4[6]} {adc_data_q_ch4[7]} {adc_data_q_ch4[8]} {adc_data_q_ch4[9]} {adc_data_q_ch4[10]} {adc_data_q_ch4[11]} {adc_data_q_ch4[12]} {adc_data_q_ch4[13]} {adc_data_q_ch4[14]} {adc_data_q_ch4[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {dac_data_i_ch2[0]} {dac_data_i_ch2[1]} {dac_data_i_ch2[2]} {dac_data_i_ch2[3]} {dac_data_i_ch2[4]} {dac_data_i_ch2[5]} {dac_data_i_ch2[6]} {dac_data_i_ch2[7]} {dac_data_i_ch2[8]} {dac_data_i_ch2[9]} {dac_data_i_ch2[10]} {dac_data_i_ch2[11]} {dac_data_i_ch2[12]} {dac_data_i_ch2[13]} {dac_data_i_ch2[14]} {dac_data_i_ch2[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 8 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {dac_tready[0]} {dac_tready[1]} {dac_tready[2]} {dac_tready[3]} {dac_tready[4]} {dac_tready[5]} {dac_tready[6]} {dac_tready[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 16 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {adc_data_q_ch1[0]} {adc_data_q_ch1[1]} {adc_data_q_ch1[2]} {adc_data_q_ch1[3]} {adc_data_q_ch1[4]} {adc_data_q_ch1[5]} {adc_data_q_ch1[6]} {adc_data_q_ch1[7]} {adc_data_q_ch1[8]} {adc_data_q_ch1[9]} {adc_data_q_ch1[10]} {adc_data_q_ch1[11]} {adc_data_q_ch1[12]} {adc_data_q_ch1[13]} {adc_data_q_ch1[14]} {adc_data_q_ch1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 16 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {adc_data_q_ch2[0]} {adc_data_q_ch2[1]} {adc_data_q_ch2[2]} {adc_data_q_ch2[3]} {adc_data_q_ch2[4]} {adc_data_q_ch2[5]} {adc_data_q_ch2[6]} {adc_data_q_ch2[7]} {adc_data_q_ch2[8]} {adc_data_q_ch2[9]} {adc_data_q_ch2[10]} {adc_data_q_ch2[11]} {adc_data_q_ch2[12]} {adc_data_q_ch2[13]} {adc_data_q_ch2[14]} {adc_data_q_ch2[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 16 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {dac_data_i_ch6[0]} {dac_data_i_ch6[1]} {dac_data_i_ch6[2]} {dac_data_i_ch6[3]} {dac_data_i_ch6[4]} {dac_data_i_ch6[5]} {dac_data_i_ch6[6]} {dac_data_i_ch6[7]} {dac_data_i_ch6[8]} {dac_data_i_ch6[9]} {dac_data_i_ch6[10]} {dac_data_i_ch6[11]} {dac_data_i_ch6[12]} {dac_data_i_ch6[13]} {dac_data_i_ch6[14]} {dac_data_i_ch6[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 16 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {dac_data_q_ch3[0]} {dac_data_q_ch3[1]} {dac_data_q_ch3[2]} {dac_data_q_ch3[3]} {dac_data_q_ch3[4]} {dac_data_q_ch3[5]} {dac_data_q_ch3[6]} {dac_data_q_ch3[7]} {dac_data_q_ch3[8]} {dac_data_q_ch3[9]} {dac_data_q_ch3[10]} {dac_data_q_ch3[11]} {dac_data_q_ch3[12]} {dac_data_q_ch3[13]} {dac_data_q_ch3[14]} {dac_data_q_ch3[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 64 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {phase_dds_in[0]} {phase_dds_in[1]} {phase_dds_in[2]} {phase_dds_in[3]} {phase_dds_in[4]} {phase_dds_in[5]} {phase_dds_in[6]} {phase_dds_in[7]} {phase_dds_in[8]} {phase_dds_in[9]} {phase_dds_in[10]} {phase_dds_in[11]} {phase_dds_in[12]} {phase_dds_in[13]} {phase_dds_in[14]} {phase_dds_in[15]} {phase_dds_in[16]} {phase_dds_in[17]} {phase_dds_in[18]} {phase_dds_in[19]} {phase_dds_in[20]} {phase_dds_in[21]} {phase_dds_in[22]} {phase_dds_in[23]} {phase_dds_in[24]} {phase_dds_in[25]} {phase_dds_in[26]} {phase_dds_in[27]} {phase_dds_in[28]} {phase_dds_in[29]} {phase_dds_in[30]} {phase_dds_in[31]} {phase_dds_in[32]} {phase_dds_in[33]} {phase_dds_in[34]} {phase_dds_in[35]} {phase_dds_in[36]} {phase_dds_in[37]} {phase_dds_in[38]} {phase_dds_in[39]} {phase_dds_in[40]} {phase_dds_in[41]} {phase_dds_in[42]} {phase_dds_in[43]} {phase_dds_in[44]} {phase_dds_in[45]} {phase_dds_in[46]} {phase_dds_in[47]} {phase_dds_in[48]} {phase_dds_in[49]} {phase_dds_in[50]} {phase_dds_in[51]} {phase_dds_in[52]} {phase_dds_in[53]} {phase_dds_in[54]} {phase_dds_in[55]} {phase_dds_in[56]} {phase_dds_in[57]} {phase_dds_in[58]} {phase_dds_in[59]} {phase_dds_in[60]} {phase_dds_in[61]} {phase_dds_in[62]} {phase_dds_in[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 16 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {dac_data_i_ch8[0]} {dac_data_i_ch8[1]} {dac_data_i_ch8[2]} {dac_data_i_ch8[3]} {dac_data_i_ch8[4]} {dac_data_i_ch8[5]} {dac_data_i_ch8[6]} {dac_data_i_ch8[7]} {dac_data_i_ch8[8]} {dac_data_i_ch8[9]} {dac_data_i_ch8[10]} {dac_data_i_ch8[11]} {dac_data_i_ch8[12]} {dac_data_i_ch8[13]} {dac_data_i_ch8[14]} {dac_data_i_ch8[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 16 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {adc_data_q_ch5[0]} {adc_data_q_ch5[1]} {adc_data_q_ch5[2]} {adc_data_q_ch5[3]} {adc_data_q_ch5[4]} {adc_data_q_ch5[5]} {adc_data_q_ch5[6]} {adc_data_q_ch5[7]} {adc_data_q_ch5[8]} {adc_data_q_ch5[9]} {adc_data_q_ch5[10]} {adc_data_q_ch5[11]} {adc_data_q_ch5[12]} {adc_data_q_ch5[13]} {adc_data_q_ch5[14]} {adc_data_q_ch5[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 16 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {adc_data_q_ch8[0]} {adc_data_q_ch8[1]} {adc_data_q_ch8[2]} {adc_data_q_ch8[3]} {adc_data_q_ch8[4]} {adc_data_q_ch8[5]} {adc_data_q_ch8[6]} {adc_data_q_ch8[7]} {adc_data_q_ch8[8]} {adc_data_q_ch8[9]} {adc_data_q_ch8[10]} {adc_data_q_ch8[11]} {adc_data_q_ch8[12]} {adc_data_q_ch8[13]} {adc_data_q_ch8[14]} {adc_data_q_ch8[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 16 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {dac_data_q_ch5[0]} {dac_data_q_ch5[1]} {dac_data_q_ch5[2]} {dac_data_q_ch5[3]} {dac_data_q_ch5[4]} {dac_data_q_ch5[5]} {dac_data_q_ch5[6]} {dac_data_q_ch5[7]} {dac_data_q_ch5[8]} {dac_data_q_ch5[9]} {dac_data_q_ch5[10]} {dac_data_q_ch5[11]} {dac_data_q_ch5[12]} {dac_data_q_ch5[13]} {dac_data_q_ch5[14]} {dac_data_q_ch5[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 16 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {dac_data_i_ch1[0]} {dac_data_i_ch1[1]} {dac_data_i_ch1[2]} {dac_data_i_ch1[3]} {dac_data_i_ch1[4]} {dac_data_i_ch1[5]} {dac_data_i_ch1[6]} {dac_data_i_ch1[7]} {dac_data_i_ch1[8]} {dac_data_i_ch1[9]} {dac_data_i_ch1[10]} {dac_data_i_ch1[11]} {dac_data_i_ch1[12]} {dac_data_i_ch1[13]} {dac_data_i_ch1[14]} {dac_data_i_ch1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 16 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {dac_data_q_ch6[0]} {dac_data_q_ch6[1]} {dac_data_q_ch6[2]} {dac_data_q_ch6[3]} {dac_data_q_ch6[4]} {dac_data_q_ch6[5]} {dac_data_q_ch6[6]} {dac_data_q_ch6[7]} {dac_data_q_ch6[8]} {dac_data_q_ch6[9]} {dac_data_q_ch6[10]} {dac_data_q_ch6[11]} {dac_data_q_ch6[12]} {dac_data_q_ch6[13]} {dac_data_q_ch6[14]} {dac_data_q_ch6[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 16 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {dac_data_q_ch4[0]} {dac_data_q_ch4[1]} {dac_data_q_ch4[2]} {dac_data_q_ch4[3]} {dac_data_q_ch4[4]} {dac_data_q_ch4[5]} {dac_data_q_ch4[6]} {dac_data_q_ch4[7]} {dac_data_q_ch4[8]} {dac_data_q_ch4[9]} {dac_data_q_ch4[10]} {dac_data_q_ch4[11]} {dac_data_q_ch4[12]} {dac_data_q_ch4[13]} {dac_data_q_ch4[14]} {dac_data_q_ch4[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 128 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {dds_data[0]} {dds_data[1]} {dds_data[2]} {dds_data[3]} {dds_data[4]} {dds_data[5]} {dds_data[6]} {dds_data[7]} {dds_data[8]} {dds_data[9]} {dds_data[10]} {dds_data[11]} {dds_data[12]} {dds_data[13]} {dds_data[14]} {dds_data[15]} {dds_data[16]} {dds_data[17]} {dds_data[18]} {dds_data[19]} {dds_data[20]} {dds_data[21]} {dds_data[22]} {dds_data[23]} {dds_data[24]} {dds_data[25]} {dds_data[26]} {dds_data[27]} {dds_data[28]} {dds_data[29]} {dds_data[30]} {dds_data[31]} {dds_data[32]} {dds_data[33]} {dds_data[34]} {dds_data[35]} {dds_data[36]} {dds_data[37]} {dds_data[38]} {dds_data[39]} {dds_data[40]} {dds_data[41]} {dds_data[42]} {dds_data[43]} {dds_data[44]} {dds_data[45]} {dds_data[46]} {dds_data[47]} {dds_data[48]} {dds_data[49]} {dds_data[50]} {dds_data[51]} {dds_data[52]} {dds_data[53]} {dds_data[54]} {dds_data[55]} {dds_data[56]} {dds_data[57]} {dds_data[58]} {dds_data[59]} {dds_data[60]} {dds_data[61]} {dds_data[62]} {dds_data[63]} {dds_data[64]} {dds_data[65]} {dds_data[66]} {dds_data[67]} {dds_data[68]} {dds_data[69]} {dds_data[70]} {dds_data[71]} {dds_data[72]} {dds_data[73]} {dds_data[74]} {dds_data[75]} {dds_data[76]} {dds_data[77]} {dds_data[78]} {dds_data[79]} {dds_data[80]} {dds_data[81]} {dds_data[82]} {dds_data[83]} {dds_data[84]} {dds_data[85]} {dds_data[86]} {dds_data[87]} {dds_data[88]} {dds_data[89]} {dds_data[90]} {dds_data[91]} {dds_data[92]} {dds_data[93]} {dds_data[94]} {dds_data[95]} {dds_data[96]} {dds_data[97]} {dds_data[98]} {dds_data[99]} {dds_data[100]} {dds_data[101]} {dds_data[102]} {dds_data[103]} {dds_data[104]} {dds_data[105]} {dds_data[106]} {dds_data[107]} {dds_data[108]} {dds_data[109]} {dds_data[110]} {dds_data[111]} {dds_data[112]} {dds_data[113]} {dds_data[114]} {dds_data[115]} {dds_data[116]} {dds_data[117]} {dds_data[118]} {dds_data[119]} {dds_data[120]} {dds_data[121]} {dds_data[122]} {dds_data[123]} {dds_data[124]} {dds_data[125]} {dds_data[126]} {dds_data[127]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 16 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {adc_tvalid[0]} {adc_tvalid[1]} {adc_tvalid[2]} {adc_tvalid[3]} {adc_tvalid[4]} {adc_tvalid[5]} {adc_tvalid[6]} {adc_tvalid[7]} {adc_tvalid[8]} {adc_tvalid[9]} {adc_tvalid[10]} {adc_tvalid[11]} {adc_tvalid[12]} {adc_tvalid[13]} {adc_tvalid[14]} {adc_tvalid[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 16 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {dac_data_i_ch5[0]} {dac_data_i_ch5[1]} {dac_data_i_ch5[2]} {dac_data_i_ch5[3]} {dac_data_i_ch5[4]} {dac_data_i_ch5[5]} {dac_data_i_ch5[6]} {dac_data_i_ch5[7]} {dac_data_i_ch5[8]} {dac_data_i_ch5[9]} {dac_data_i_ch5[10]} {dac_data_i_ch5[11]} {dac_data_i_ch5[12]} {dac_data_i_ch5[13]} {dac_data_i_ch5[14]} {dac_data_i_ch5[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 16 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {adc_data_q_ch6[0]} {adc_data_q_ch6[1]} {adc_data_q_ch6[2]} {adc_data_q_ch6[3]} {adc_data_q_ch6[4]} {adc_data_q_ch6[5]} {adc_data_q_ch6[6]} {adc_data_q_ch6[7]} {adc_data_q_ch6[8]} {adc_data_q_ch6[9]} {adc_data_q_ch6[10]} {adc_data_q_ch6[11]} {adc_data_q_ch6[12]} {adc_data_q_ch6[13]} {adc_data_q_ch6[14]} {adc_data_q_ch6[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 16 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {dac_data_q_ch2[0]} {dac_data_q_ch2[1]} {dac_data_q_ch2[2]} {dac_data_q_ch2[3]} {dac_data_q_ch2[4]} {dac_data_q_ch2[5]} {dac_data_q_ch2[6]} {dac_data_q_ch2[7]} {dac_data_q_ch2[8]} {dac_data_q_ch2[9]} {dac_data_q_ch2[10]} {dac_data_q_ch2[11]} {dac_data_q_ch2[12]} {dac_data_q_ch2[13]} {dac_data_q_ch2[14]} {dac_data_q_ch2[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 16 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {dac_data_q_ch7[0]} {dac_data_q_ch7[1]} {dac_data_q_ch7[2]} {dac_data_q_ch7[3]} {dac_data_q_ch7[4]} {dac_data_q_ch7[5]} {dac_data_q_ch7[6]} {dac_data_q_ch7[7]} {dac_data_q_ch7[8]} {dac_data_q_ch7[9]} {dac_data_q_ch7[10]} {dac_data_q_ch7[11]} {dac_data_q_ch7[12]} {dac_data_q_ch7[13]} {dac_data_q_ch7[14]} {dac_data_q_ch7[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 16 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {dac_data_i_ch7[0]} {dac_data_i_ch7[1]} {dac_data_i_ch7[2]} {dac_data_i_ch7[3]} {dac_data_i_ch7[4]} {dac_data_i_ch7[5]} {dac_data_i_ch7[6]} {dac_data_i_ch7[7]} {dac_data_i_ch7[8]} {dac_data_i_ch7[9]} {dac_data_i_ch7[10]} {dac_data_i_ch7[11]} {dac_data_i_ch7[12]} {dac_data_i_ch7[13]} {dac_data_i_ch7[14]} {dac_data_i_ch7[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 16 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {adc_data_q_ch7[0]} {adc_data_q_ch7[1]} {adc_data_q_ch7[2]} {adc_data_q_ch7[3]} {adc_data_q_ch7[4]} {adc_data_q_ch7[5]} {adc_data_q_ch7[6]} {adc_data_q_ch7[7]} {adc_data_q_ch7[8]} {adc_data_q_ch7[9]} {adc_data_q_ch7[10]} {adc_data_q_ch7[11]} {adc_data_q_ch7[12]} {adc_data_q_ch7[13]} {adc_data_q_ch7[14]} {adc_data_q_ch7[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 16 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {dac_data_i_ch3[0]} {dac_data_i_ch3[1]} {dac_data_i_ch3[2]} {dac_data_i_ch3[3]} {dac_data_i_ch3[4]} {dac_data_i_ch3[5]} {dac_data_i_ch3[6]} {dac_data_i_ch3[7]} {dac_data_i_ch3[8]} {dac_data_i_ch3[9]} {dac_data_i_ch3[10]} {dac_data_i_ch3[11]} {dac_data_i_ch3[12]} {dac_data_i_ch3[13]} {dac_data_i_ch3[14]} {dac_data_i_ch3[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 16 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {dac_data_q_ch1[0]} {dac_data_q_ch1[1]} {dac_data_q_ch1[2]} {dac_data_q_ch1[3]} {dac_data_q_ch1[4]} {dac_data_q_ch1[5]} {dac_data_q_ch1[6]} {dac_data_q_ch1[7]} {dac_data_q_ch1[8]} {dac_data_q_ch1[9]} {dac_data_q_ch1[10]} {dac_data_q_ch1[11]} {dac_data_q_ch1[12]} {dac_data_q_ch1[13]} {dac_data_q_ch1[14]} {dac_data_q_ch1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 16 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {adc_data_q_ch3[0]} {adc_data_q_ch3[1]} {adc_data_q_ch3[2]} {adc_data_q_ch3[3]} {adc_data_q_ch3[4]} {adc_data_q_ch3[5]} {adc_data_q_ch3[6]} {adc_data_q_ch3[7]} {adc_data_q_ch3[8]} {adc_data_q_ch3[9]} {adc_data_q_ch3[10]} {adc_data_q_ch3[11]} {adc_data_q_ch3[12]} {adc_data_q_ch3[13]} {adc_data_q_ch3[14]} {adc_data_q_ch3[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 16 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {phase_inc_reg[0]} {phase_inc_reg[1]} {phase_inc_reg[2]} {phase_inc_reg[3]} {phase_inc_reg[4]} {phase_inc_reg[5]} {phase_inc_reg[6]} {phase_inc_reg[7]} {phase_inc_reg[8]} {phase_inc_reg[9]} {phase_inc_reg[10]} {phase_inc_reg[11]} {phase_inc_reg[12]} {phase_inc_reg[13]} {phase_inc_reg[14]} {phase_inc_reg[15]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets data_clk]
